// =============================================
// 保育施設静的データ（Phase B1）
// =============================================
// データソース:
// - 施設定員: こども家庭庁「保育所等関連状況取りまとめ」令和6年（2024）4月1日時点
//   ※ 2020〜2023年の定員は年率成長率から逆算した推計値（認可保育所+3%/年, こども園+15%/年, 小規模+6%/年）
// - 施設数: 定員÷平均規模（認可保育所90名, こども園150名, 小規模15名）による推計値
// - 待機児童数: 東京都福祉局・こども家庭庁「都内の保育サービスの状況」各年4月1日時点
// - 出生数: 東京都統計局「人口の動き」各暦年

export type FacilityCategory = '認可保育所' | '認定こども園' | '小規模保育等'

export interface SeedFacility {
  ward:        string
  fiscal_year: number
  category:    FacilityCategory
  count:       number  // 推計値（定員÷平均規模）
  capacity:    number
  estimated:   boolean // true = 推計値（実データは 2024年度のみ）
}

export interface SeedWaiting {
  ward:                 string
  fiscal_year:          number
  total_waiting:        number  // 厚生労働省定義の待機児童数
  total_hidden_waiting: number | null  // 利用保留（隠れ待機）- データなし時 null
}

export interface SeedBirth {
  ward:        string
  fiscal_year: number
  birth_count: number
}

export const SEED_FACILITIES: SeedFacility[] = [
  { ward: '千代田区', fiscal_year: 2020, category: '認可保育所', count: 19, capacity: 1682, estimated: true },
  { ward: '千代田区', fiscal_year: 2020, category: '小規模保育等', count: 7, capacity: 101, estimated: true },
  { ward: '千代田区', fiscal_year: 2021, category: '認可保育所', count: 19, capacity: 1732, estimated: true },
  { ward: '千代田区', fiscal_year: 2021, category: '小規模保育等', count: 7, capacity: 107, estimated: true },
  { ward: '千代田区', fiscal_year: 2022, category: '認可保育所', count: 20, capacity: 1784, estimated: true },
  { ward: '千代田区', fiscal_year: 2022, category: '小規模保育等', count: 8, capacity: 113, estimated: true },
  { ward: '千代田区', fiscal_year: 2023, category: '認可保育所', count: 20, capacity: 1838, estimated: true },
  { ward: '千代田区', fiscal_year: 2023, category: '小規模保育等', count: 8, capacity: 120, estimated: true },
  { ward: '千代田区', fiscal_year: 2024, category: '認可保育所', count: 21, capacity: 1893, estimated: false },
  { ward: '千代田区', fiscal_year: 2024, category: '小規模保育等', count: 8, capacity: 127, estimated: false },
  { ward: '中央区', fiscal_year: 2020, category: '認可保育所', count: 63, capacity: 5645, estimated: true },
  { ward: '中央区', fiscal_year: 2020, category: '認定こども園', count: 1, capacity: 98, estimated: true },
  { ward: '中央区', fiscal_year: 2020, category: '小規模保育等', count: 3, capacity: 44, estimated: true },
  { ward: '中央区', fiscal_year: 2021, category: '認可保育所', count: 65, capacity: 5815, estimated: true },
  { ward: '中央区', fiscal_year: 2021, category: '認定こども園', count: 1, capacity: 113, estimated: true },
  { ward: '中央区', fiscal_year: 2021, category: '小規模保育等', count: 3, capacity: 46, estimated: true },
  { ward: '中央区', fiscal_year: 2022, category: '認可保育所', count: 67, capacity: 5989, estimated: true },
  { ward: '中央区', fiscal_year: 2022, category: '認定こども園', count: 1, capacity: 130, estimated: true },
  { ward: '中央区', fiscal_year: 2022, category: '小規模保育等', count: 3, capacity: 49, estimated: true },
  { ward: '中央区', fiscal_year: 2023, category: '認可保育所', count: 69, capacity: 6169, estimated: true },
  { ward: '中央区', fiscal_year: 2023, category: '認定こども園', count: 1, capacity: 150, estimated: true },
  { ward: '中央区', fiscal_year: 2023, category: '小規模保育等', count: 3, capacity: 52, estimated: true },
  { ward: '中央区', fiscal_year: 2024, category: '認可保育所', count: 71, capacity: 6354, estimated: false },
  { ward: '中央区', fiscal_year: 2024, category: '認定こども園', count: 1, capacity: 172, estimated: false },
  { ward: '中央区', fiscal_year: 2024, category: '小規模保育等', count: 4, capacity: 55, estimated: false },
  { ward: '港区', fiscal_year: 2020, category: '認可保育所', count: 68, capacity: 6085, estimated: true },
  { ward: '港区', fiscal_year: 2020, category: '小規模保育等', count: 11, capacity: 159, estimated: true },
  { ward: '港区', fiscal_year: 2021, category: '認可保育所', count: 70, capacity: 6268, estimated: true },
  { ward: '港区', fiscal_year: 2021, category: '小規模保育等', count: 11, capacity: 169, estimated: true },
  { ward: '港区', fiscal_year: 2022, category: '認可保育所', count: 72, capacity: 6456, estimated: true },
  { ward: '港区', fiscal_year: 2022, category: '小規模保育等', count: 12, capacity: 179, estimated: true },
  { ward: '港区', fiscal_year: 2023, category: '認可保育所', count: 74, capacity: 6650, estimated: true },
  { ward: '港区', fiscal_year: 2023, category: '小規模保育等', count: 13, capacity: 190, estimated: true },
  { ward: '港区', fiscal_year: 2024, category: '認可保育所', count: 76, capacity: 6849, estimated: false },
  { ward: '港区', fiscal_year: 2024, category: '小規模保育等', count: 13, capacity: 201, estimated: false },
  { ward: '新宿区', fiscal_year: 2020, category: '認可保育所', count: 74, capacity: 6670, estimated: true },
  { ward: '新宿区', fiscal_year: 2020, category: '認定こども園', count: 1, capacity: 205, estimated: true },
  { ward: '新宿区', fiscal_year: 2020, category: '小規模保育等', count: 9, capacity: 129, estimated: true },
  { ward: '新宿区', fiscal_year: 2021, category: '認可保育所', count: 76, capacity: 6870, estimated: true },
  { ward: '新宿区', fiscal_year: 2021, category: '認定こども園', count: 2, capacity: 236, estimated: true },
  { ward: '新宿区', fiscal_year: 2021, category: '小規模保育等', count: 9, capacity: 137, estimated: true },
  { ward: '新宿区', fiscal_year: 2022, category: '認可保育所', count: 79, capacity: 7076, estimated: true },
  { ward: '新宿区', fiscal_year: 2022, category: '認定こども園', count: 2, capacity: 271, estimated: true },
  { ward: '新宿区', fiscal_year: 2022, category: '小規模保育等', count: 10, capacity: 145, estimated: true },
  { ward: '新宿区', fiscal_year: 2023, category: '認可保育所', count: 81, capacity: 7288, estimated: true },
  { ward: '新宿区', fiscal_year: 2023, category: '認定こども園', count: 2, capacity: 312, estimated: true },
  { ward: '新宿区', fiscal_year: 2023, category: '小規模保育等', count: 10, capacity: 154, estimated: true },
  { ward: '新宿区', fiscal_year: 2024, category: '認可保育所', count: 83, capacity: 7507, estimated: false },
  { ward: '新宿区', fiscal_year: 2024, category: '認定こども園', count: 2, capacity: 359, estimated: false },
  { ward: '新宿区', fiscal_year: 2024, category: '小規模保育等', count: 11, capacity: 163, estimated: false },
  { ward: '文京区', fiscal_year: 2020, category: '認可保育所', count: 69, capacity: 6235, estimated: true },
  { ward: '文京区', fiscal_year: 2020, category: '小規模保育等', count: 16, capacity: 237, estimated: true },
  { ward: '文京区', fiscal_year: 2021, category: '認可保育所', count: 71, capacity: 6422, estimated: true },
  { ward: '文京区', fiscal_year: 2021, category: '小規模保育等', count: 17, capacity: 251, estimated: true },
  { ward: '文京区', fiscal_year: 2022, category: '認可保育所', count: 74, capacity: 6615, estimated: true },
  { ward: '文京区', fiscal_year: 2022, category: '小規模保育等', count: 18, capacity: 266, estimated: true },
  { ward: '文京区', fiscal_year: 2023, category: '認可保育所', count: 76, capacity: 6814, estimated: true },
  { ward: '文京区', fiscal_year: 2023, category: '小規模保育等', count: 19, capacity: 282, estimated: true },
  { ward: '文京区', fiscal_year: 2024, category: '認可保育所', count: 78, capacity: 7018, estimated: false },
  { ward: '文京区', fiscal_year: 2024, category: '小規模保育等', count: 20, capacity: 299, estimated: false },
  { ward: '台東区', fiscal_year: 2020, category: '認可保育所', count: 40, capacity: 3597, estimated: true },
  { ward: '台東区', fiscal_year: 2020, category: '認定こども園', count: 1, capacity: 42, estimated: true },
  { ward: '台東区', fiscal_year: 2020, category: '小規模保育等', count: 14, capacity: 209, estimated: true },
  { ward: '台東区', fiscal_year: 2021, category: '認可保育所', count: 41, capacity: 3705, estimated: true },
  { ward: '台東区', fiscal_year: 2021, category: '認定こども園', count: 1, capacity: 48, estimated: true },
  { ward: '台東区', fiscal_year: 2021, category: '小規模保育等', count: 15, capacity: 222, estimated: true },
  { ward: '台東区', fiscal_year: 2022, category: '認可保育所', count: 42, capacity: 3817, estimated: true },
  { ward: '台東区', fiscal_year: 2022, category: '認定こども園', count: 1, capacity: 55, estimated: true },
  { ward: '台東区', fiscal_year: 2022, category: '小規模保育等', count: 16, capacity: 235, estimated: true },
  { ward: '台東区', fiscal_year: 2023, category: '認可保育所', count: 44, capacity: 3931, estimated: true },
  { ward: '台東区', fiscal_year: 2023, category: '認定こども園', count: 1, capacity: 63, estimated: true },
  { ward: '台東区', fiscal_year: 2023, category: '小規模保育等', count: 17, capacity: 249, estimated: true },
  { ward: '台東区', fiscal_year: 2024, category: '認可保育所', count: 45, capacity: 4049, estimated: false },
  { ward: '台東区', fiscal_year: 2024, category: '認定こども園', count: 1, capacity: 73, estimated: false },
  { ward: '台東区', fiscal_year: 2024, category: '小規模保育等', count: 18, capacity: 264, estimated: false },
  { ward: '墨田区', fiscal_year: 2020, category: '認可保育所', count: 67, capacity: 6071, estimated: true },
  { ward: '墨田区', fiscal_year: 2020, category: '認定こども園', count: 2, capacity: 277, estimated: true },
  { ward: '墨田区', fiscal_year: 2020, category: '小規模保育等', count: 8, capacity: 122, estimated: true },
  { ward: '墨田区', fiscal_year: 2021, category: '認可保育所', count: 69, capacity: 6253, estimated: true },
  { ward: '墨田区', fiscal_year: 2021, category: '認定こども園', count: 2, capacity: 319, estimated: true },
  { ward: '墨田区', fiscal_year: 2021, category: '小規模保育等', count: 9, capacity: 129, estimated: true },
  { ward: '墨田区', fiscal_year: 2022, category: '認可保育所', count: 72, capacity: 6441, estimated: true },
  { ward: '墨田区', fiscal_year: 2022, category: '認定こども園', count: 2, capacity: 367, estimated: true },
  { ward: '墨田区', fiscal_year: 2022, category: '小規模保育等', count: 9, capacity: 137, estimated: true },
  { ward: '墨田区', fiscal_year: 2023, category: '認可保育所', count: 74, capacity: 6634, estimated: true },
  { ward: '墨田区', fiscal_year: 2023, category: '認定こども園', count: 3, capacity: 422, estimated: true },
  { ward: '墨田区', fiscal_year: 2023, category: '小規模保育等', count: 10, capacity: 145, estimated: true },
  { ward: '墨田区', fiscal_year: 2024, category: '認可保育所', count: 76, capacity: 6833, estimated: false },
  { ward: '墨田区', fiscal_year: 2024, category: '認定こども園', count: 3, capacity: 485, estimated: false },
  { ward: '墨田区', fiscal_year: 2024, category: '小規模保育等', count: 10, capacity: 154, estimated: false },
  { ward: '江東区', fiscal_year: 2020, category: '認可保育所', count: 158, capacity: 14248, estimated: true },
  { ward: '江東区', fiscal_year: 2020, category: '認定こども園', count: 1, capacity: 208, estimated: true },
  { ward: '江東区', fiscal_year: 2020, category: '小規模保育等', count: 15, capacity: 232, estimated: true },
  { ward: '江東区', fiscal_year: 2021, category: '認可保育所', count: 163, capacity: 14675, estimated: true },
  { ward: '江東区', fiscal_year: 2021, category: '認定こども園', count: 2, capacity: 239, estimated: true },
  { ward: '江東区', fiscal_year: 2021, category: '小規模保育等', count: 16, capacity: 246, estimated: true },
  { ward: '江東区', fiscal_year: 2022, category: '認可保育所', count: 168, capacity: 15115, estimated: true },
  { ward: '江東区', fiscal_year: 2022, category: '認定こども園', count: 2, capacity: 275, estimated: true },
  { ward: '江東区', fiscal_year: 2022, category: '小規模保育等', count: 17, capacity: 261, estimated: true },
  { ward: '江東区', fiscal_year: 2023, category: '認可保育所', count: 173, capacity: 15569, estimated: true },
  { ward: '江東区', fiscal_year: 2023, category: '認定こども園', count: 2, capacity: 317, estimated: true },
  { ward: '江東区', fiscal_year: 2023, category: '小規模保育等', count: 18, capacity: 276, estimated: true },
  { ward: '江東区', fiscal_year: 2024, category: '認可保育所', count: 178, capacity: 16036, estimated: false },
  { ward: '江東区', fiscal_year: 2024, category: '認定こども園', count: 2, capacity: 364, estimated: false },
  { ward: '江東区', fiscal_year: 2024, category: '小規模保育等', count: 20, capacity: 293, estimated: false },
  { ward: '品川区', fiscal_year: 2020, category: '認可保育所', count: 119, capacity: 10688, estimated: true },
  { ward: '品川区', fiscal_year: 2020, category: '小規模保育等', count: 12, capacity: 181, estimated: true },
  { ward: '品川区', fiscal_year: 2021, category: '認可保育所', count: 122, capacity: 11008, estimated: true },
  { ward: '品川区', fiscal_year: 2021, category: '小規模保育等', count: 13, capacity: 191, estimated: true },
  { ward: '品川区', fiscal_year: 2022, category: '認可保育所', count: 126, capacity: 11338, estimated: true },
  { ward: '品川区', fiscal_year: 2022, category: '小規模保育等', count: 14, capacity: 203, estimated: true },
  { ward: '品川区', fiscal_year: 2023, category: '認可保育所', count: 130, capacity: 11679, estimated: true },
  { ward: '品川区', fiscal_year: 2023, category: '小規模保育等', count: 14, capacity: 215, estimated: true },
  { ward: '品川区', fiscal_year: 2024, category: '認可保育所', count: 134, capacity: 12029, estimated: false },
  { ward: '品川区', fiscal_year: 2024, category: '小規模保育等', count: 15, capacity: 228, estimated: false },
  { ward: '目黒区', fiscal_year: 2020, category: '認可保育所', count: 72, capacity: 6439, estimated: true },
  { ward: '目黒区', fiscal_year: 2020, category: '認定こども園', count: 1, capacity: 31, estimated: true },
  { ward: '目黒区', fiscal_year: 2020, category: '小規模保育等', count: 12, capacity: 185, estimated: true },
  { ward: '目黒区', fiscal_year: 2021, category: '認可保育所', count: 74, capacity: 6632, estimated: true },
  { ward: '目黒区', fiscal_year: 2021, category: '認定こども園', count: 1, capacity: 36, estimated: true },
  { ward: '目黒区', fiscal_year: 2021, category: '小規模保育等', count: 13, capacity: 196, estimated: true },
  { ward: '目黒区', fiscal_year: 2022, category: '認可保育所', count: 76, capacity: 6831, estimated: true },
  { ward: '目黒区', fiscal_year: 2022, category: '認定こども園', count: 1, capacity: 41, estimated: true },
  { ward: '目黒区', fiscal_year: 2022, category: '小規模保育等', count: 14, capacity: 207, estimated: true },
  { ward: '目黒区', fiscal_year: 2023, category: '認可保育所', count: 78, capacity: 7036, estimated: true },
  { ward: '目黒区', fiscal_year: 2023, category: '認定こども園', count: 1, capacity: 47, estimated: true },
  { ward: '目黒区', fiscal_year: 2023, category: '小規模保育等', count: 15, capacity: 220, estimated: true },
  { ward: '目黒区', fiscal_year: 2024, category: '認可保育所', count: 81, capacity: 7247, estimated: false },
  { ward: '目黒区', fiscal_year: 2024, category: '認定こども園', count: 1, capacity: 54, estimated: false },
  { ward: '目黒区', fiscal_year: 2024, category: '小規模保育等', count: 16, capacity: 233, estimated: false },
  { ward: '大田区', fiscal_year: 2020, category: '認可保育所', count: 160, capacity: 14373, estimated: true },
  { ward: '大田区', fiscal_year: 2020, category: '小規模保育等', count: 26, capacity: 395, estimated: true },
  { ward: '大田区', fiscal_year: 2021, category: '認可保育所', count: 164, capacity: 14804, estimated: true },
  { ward: '大田区', fiscal_year: 2021, category: '小規模保育等', count: 28, capacity: 419, estimated: true },
  { ward: '大田区', fiscal_year: 2022, category: '認可保育所', count: 169, capacity: 15248, estimated: true },
  { ward: '大田区', fiscal_year: 2022, category: '小規模保育等', count: 30, capacity: 444, estimated: true },
  { ward: '大田区', fiscal_year: 2023, category: '認可保育所', count: 175, capacity: 15706, estimated: true },
  { ward: '大田区', fiscal_year: 2023, category: '小規模保育等', count: 31, capacity: 471, estimated: true },
  { ward: '大田区', fiscal_year: 2024, category: '認可保育所', count: 180, capacity: 16177, estimated: false },
  { ward: '大田区', fiscal_year: 2024, category: '小規模保育等', count: 33, capacity: 499, estimated: false },
  { ward: '世田谷区', fiscal_year: 2020, category: '認可保育所', count: 181, capacity: 16287, estimated: true },
  { ward: '世田谷区', fiscal_year: 2020, category: '認定こども園', count: 2, capacity: 361, estimated: true },
  { ward: '世田谷区', fiscal_year: 2020, category: '小規模保育等', count: 20, capacity: 301, estimated: true },
  { ward: '世田谷区', fiscal_year: 2021, category: '認可保育所', count: 186, capacity: 16775, estimated: true },
  { ward: '世田谷区', fiscal_year: 2021, category: '認定こども園', count: 3, capacity: 415, estimated: true },
  { ward: '世田谷区', fiscal_year: 2021, category: '小規模保育等', count: 21, capacity: 319, estimated: true },
  { ward: '世田谷区', fiscal_year: 2022, category: '認可保育所', count: 192, capacity: 17279, estimated: true },
  { ward: '世田谷区', fiscal_year: 2022, category: '認定こども園', count: 3, capacity: 477, estimated: true },
  { ward: '世田谷区', fiscal_year: 2022, category: '小規模保育等', count: 23, capacity: 338, estimated: true },
  { ward: '世田谷区', fiscal_year: 2023, category: '認可保育所', count: 198, capacity: 17797, estimated: true },
  { ward: '世田谷区', fiscal_year: 2023, category: '認定こども園', count: 4, capacity: 549, estimated: true },
  { ward: '世田谷区', fiscal_year: 2023, category: '小規模保育等', count: 24, capacity: 358, estimated: true },
  { ward: '世田谷区', fiscal_year: 2024, category: '認可保育所', count: 204, capacity: 18331, estimated: false },
  { ward: '世田谷区', fiscal_year: 2024, category: '認定こども園', count: 4, capacity: 631, estimated: false },
  { ward: '世田谷区', fiscal_year: 2024, category: '小規模保育等', count: 25, capacity: 380, estimated: false },
  { ward: '渋谷区', fiscal_year: 2020, category: '認可保育所', count: 59, capacity: 5324, estimated: true },
  { ward: '渋谷区', fiscal_year: 2020, category: '小規模保育等', count: 3, capacity: 52, estimated: true },
  { ward: '渋谷区', fiscal_year: 2021, category: '認可保育所', count: 61, capacity: 5484, estimated: true },
  { ward: '渋谷区', fiscal_year: 2021, category: '小規模保育等', count: 4, capacity: 55, estimated: true },
  { ward: '渋谷区', fiscal_year: 2022, category: '認可保育所', count: 63, capacity: 5648, estimated: true },
  { ward: '渋谷区', fiscal_year: 2022, category: '小規模保育等', count: 4, capacity: 59, estimated: true },
  { ward: '渋谷区', fiscal_year: 2023, category: '認可保育所', count: 65, capacity: 5817, estimated: true },
  { ward: '渋谷区', fiscal_year: 2023, category: '小規模保育等', count: 4, capacity: 62, estimated: true },
  { ward: '渋谷区', fiscal_year: 2024, category: '認可保育所', count: 67, capacity: 5992, estimated: false },
  { ward: '渋谷区', fiscal_year: 2024, category: '小規模保育等', count: 4, capacity: 66, estimated: false },
  { ward: '中野区', fiscal_year: 2020, category: '認可保育所', count: 74, capacity: 6666, estimated: true },
  { ward: '中野区', fiscal_year: 2020, category: '認定こども園', count: 1, capacity: 206, estimated: true },
  { ward: '中野区', fiscal_year: 2020, category: '小規模保育等', count: 9, capacity: 140, estimated: true },
  { ward: '中野区', fiscal_year: 2021, category: '認可保育所', count: 76, capacity: 6866, estimated: true },
  { ward: '中野区', fiscal_year: 2021, category: '認定こども園', count: 2, capacity: 237, estimated: true },
  { ward: '中野区', fiscal_year: 2021, category: '小規模保育等', count: 10, capacity: 149, estimated: true },
  { ward: '中野区', fiscal_year: 2022, category: '認可保育所', count: 79, capacity: 7072, estimated: true },
  { ward: '中野区', fiscal_year: 2022, category: '認定こども園', count: 2, capacity: 273, estimated: true },
  { ward: '中野区', fiscal_year: 2022, category: '小規模保育等', count: 11, capacity: 158, estimated: true },
  { ward: '中野区', fiscal_year: 2023, category: '認可保育所', count: 81, capacity: 7284, estimated: true },
  { ward: '中野区', fiscal_year: 2023, category: '認定こども園', count: 2, capacity: 314, estimated: true },
  { ward: '中野区', fiscal_year: 2023, category: '小規模保育等', count: 11, capacity: 167, estimated: true },
  { ward: '中野区', fiscal_year: 2024, category: '認可保育所', count: 83, capacity: 7503, estimated: false },
  { ward: '中野区', fiscal_year: 2024, category: '認定こども園', count: 2, capacity: 361, estimated: false },
  { ward: '中野区', fiscal_year: 2024, category: '小規模保育等', count: 12, capacity: 177, estimated: false },
  { ward: '杉並区', fiscal_year: 2020, category: '認可保育所', count: 146, capacity: 13138, estimated: true },
  { ward: '杉並区', fiscal_year: 2020, category: '小規模保育等', count: 28, capacity: 424, estimated: true },
  { ward: '杉並区', fiscal_year: 2021, category: '認可保育所', count: 150, capacity: 13532, estimated: true },
  { ward: '杉並区', fiscal_year: 2021, category: '小規模保育等', count: 30, capacity: 449, estimated: true },
  { ward: '杉並区', fiscal_year: 2022, category: '認可保育所', count: 155, capacity: 13938, estimated: true },
  { ward: '杉並区', fiscal_year: 2022, category: '小規模保育等', count: 32, capacity: 476, estimated: true },
  { ward: '杉並区', fiscal_year: 2023, category: '認可保育所', count: 160, capacity: 14356, estimated: true },
  { ward: '杉並区', fiscal_year: 2023, category: '小規模保育等', count: 34, capacity: 505, estimated: true },
  { ward: '杉並区', fiscal_year: 2024, category: '認可保育所', count: 164, capacity: 14787, estimated: false },
  { ward: '杉並区', fiscal_year: 2024, category: '小規模保育等', count: 36, capacity: 535, estimated: false },
  { ward: '豊島区', fiscal_year: 2020, category: '認可保育所', count: 66, capacity: 5962, estimated: true },
  { ward: '豊島区', fiscal_year: 2020, category: '認定こども園', count: 1, capacity: 6, estimated: true },
  { ward: '豊島区', fiscal_year: 2020, category: '小規模保育等', count: 11, capacity: 170, estimated: true },
  { ward: '豊島区', fiscal_year: 2021, category: '認可保育所', count: 68, capacity: 6141, estimated: true },
  { ward: '豊島区', fiscal_year: 2021, category: '認定こども園', count: 1, capacity: 7, estimated: true },
  { ward: '豊島区', fiscal_year: 2021, category: '小規模保育等', count: 12, capacity: 180, estimated: true },
  { ward: '豊島区', fiscal_year: 2022, category: '認可保育所', count: 70, capacity: 6325, estimated: true },
  { ward: '豊島区', fiscal_year: 2022, category: '認定こども園', count: 1, capacity: 8, estimated: true },
  { ward: '豊島区', fiscal_year: 2022, category: '小規模保育等', count: 13, capacity: 190, estimated: true },
  { ward: '豊島区', fiscal_year: 2023, category: '認可保育所', count: 72, capacity: 6515, estimated: true },
  { ward: '豊島区', fiscal_year: 2023, category: '認定こども園', count: 1, capacity: 9, estimated: true },
  { ward: '豊島区', fiscal_year: 2023, category: '小規模保育等', count: 13, capacity: 202, estimated: true },
  { ward: '豊島区', fiscal_year: 2024, category: '認可保育所', count: 75, capacity: 6710, estimated: false },
  { ward: '豊島区', fiscal_year: 2024, category: '認定こども園', count: 1, capacity: 10, estimated: false },
  { ward: '豊島区', fiscal_year: 2024, category: '小規模保育等', count: 14, capacity: 214, estimated: false },
  { ward: '北区', fiscal_year: 2020, category: '認可保育所', count: 91, capacity: 8172, estimated: true },
  { ward: '北区', fiscal_year: 2020, category: '認定こども園', count: 1, capacity: 129, estimated: true },
  { ward: '北区', fiscal_year: 2020, category: '小規模保育等', count: 19, capacity: 288, estimated: true },
  { ward: '北区', fiscal_year: 2021, category: '認可保育所', count: 94, capacity: 8417, estimated: true },
  { ward: '北区', fiscal_year: 2021, category: '認定こども園', count: 1, capacity: 148, estimated: true },
  { ward: '北区', fiscal_year: 2021, category: '小規模保育等', count: 20, capacity: 305, estimated: true },
  { ward: '北区', fiscal_year: 2022, category: '認可保育所', count: 96, capacity: 8670, estimated: true },
  { ward: '北区', fiscal_year: 2022, category: '認定こども園', count: 1, capacity: 170, estimated: true },
  { ward: '北区', fiscal_year: 2022, category: '小規模保育等', count: 22, capacity: 323, estimated: true },
  { ward: '北区', fiscal_year: 2023, category: '認可保育所', count: 99, capacity: 8930, estimated: true },
  { ward: '北区', fiscal_year: 2023, category: '認定こども園', count: 1, capacity: 196, estimated: true },
  { ward: '北区', fiscal_year: 2023, category: '小規模保育等', count: 23, capacity: 342, estimated: true },
  { ward: '北区', fiscal_year: 2024, category: '認可保育所', count: 102, capacity: 9198, estimated: false },
  { ward: '北区', fiscal_year: 2024, category: '認定こども園', count: 2, capacity: 225, estimated: false },
  { ward: '北区', fiscal_year: 2024, category: '小規模保育等', count: 24, capacity: 363, estimated: false },
  { ward: '荒川区', fiscal_year: 2020, category: '認可保育所', count: 60, capacity: 5359, estimated: true },
  { ward: '荒川区', fiscal_year: 2020, category: '小規模保育等', count: 4, capacity: 55, estimated: true },
  { ward: '荒川区', fiscal_year: 2021, category: '認可保育所', count: 61, capacity: 5520, estimated: true },
  { ward: '荒川区', fiscal_year: 2021, category: '小規模保育等', count: 4, capacity: 58, estimated: true },
  { ward: '荒川区', fiscal_year: 2022, category: '認可保育所', count: 63, capacity: 5686, estimated: true },
  { ward: '荒川区', fiscal_year: 2022, category: '小規模保育等', count: 4, capacity: 61, estimated: true },
  { ward: '荒川区', fiscal_year: 2023, category: '認可保育所', count: 65, capacity: 5856, estimated: true },
  { ward: '荒川区', fiscal_year: 2023, category: '小規模保育等', count: 4, capacity: 65, estimated: true },
  { ward: '荒川区', fiscal_year: 2024, category: '認可保育所', count: 67, capacity: 6032, estimated: false },
  { ward: '荒川区', fiscal_year: 2024, category: '小規模保育等', count: 5, capacity: 69, estimated: false },
  { ward: '板橋区', fiscal_year: 2020, category: '認可保育所', count: 121, capacity: 10872, estimated: true },
  { ward: '板橋区', fiscal_year: 2020, category: '認定こども園', count: 1, capacity: 90, estimated: true },
  { ward: '板橋区', fiscal_year: 2020, category: '小規模保育等', count: 47, capacity: 705, estimated: true },
  { ward: '板橋区', fiscal_year: 2021, category: '認可保育所', count: 124, capacity: 11198, estimated: true },
  { ward: '板橋区', fiscal_year: 2021, category: '認定こども園', count: 1, capacity: 103, estimated: true },
  { ward: '板橋区', fiscal_year: 2021, category: '小規模保育等', count: 50, capacity: 747, estimated: true },
  { ward: '板橋区', fiscal_year: 2022, category: '認可保育所', count: 128, capacity: 11534, estimated: true },
  { ward: '板橋区', fiscal_year: 2022, category: '認定こども園', count: 1, capacity: 119, estimated: true },
  { ward: '板橋区', fiscal_year: 2022, category: '小規模保育等', count: 53, capacity: 792, estimated: true },
  { ward: '板橋区', fiscal_year: 2023, category: '認可保育所', count: 132, capacity: 11880, estimated: true },
  { ward: '板橋区', fiscal_year: 2023, category: '認定こども園', count: 1, capacity: 137, estimated: true },
  { ward: '板橋区', fiscal_year: 2023, category: '小規模保育等', count: 56, capacity: 840, estimated: true },
  { ward: '板橋区', fiscal_year: 2024, category: '認可保育所', count: 136, capacity: 12236, estimated: false },
  { ward: '板橋区', fiscal_year: 2024, category: '認定こども園', count: 1, capacity: 157, estimated: false },
  { ward: '板橋区', fiscal_year: 2024, category: '小規模保育等', count: 59, capacity: 890, estimated: false },
  { ward: '練馬区', fiscal_year: 2020, category: '認可保育所', count: 173, capacity: 15590, estimated: true },
  { ward: '練馬区', fiscal_year: 2020, category: '認定こども園', count: 1, capacity: 112, estimated: true },
  { ward: '練馬区', fiscal_year: 2020, category: '小規模保育等', count: 55, capacity: 826, estimated: true },
  { ward: '練馬区', fiscal_year: 2021, category: '認可保育所', count: 178, capacity: 16058, estimated: true },
  { ward: '練馬区', fiscal_year: 2021, category: '認定こども園', count: 1, capacity: 129, estimated: true },
  { ward: '練馬区', fiscal_year: 2021, category: '小規模保育等', count: 58, capacity: 876, estimated: true },
  { ward: '練馬区', fiscal_year: 2022, category: '認可保育所', count: 184, capacity: 16540, estimated: true },
  { ward: '練馬区', fiscal_year: 2022, category: '認定こども園', count: 1, capacity: 148, estimated: true },
  { ward: '練馬区', fiscal_year: 2022, category: '小規模保育等', count: 62, capacity: 928, estimated: true },
  { ward: '練馬区', fiscal_year: 2023, category: '認可保育所', count: 189, capacity: 17036, estimated: true },
  { ward: '練馬区', fiscal_year: 2023, category: '認定こども園', count: 1, capacity: 170, estimated: true },
  { ward: '練馬区', fiscal_year: 2023, category: '小規模保育等', count: 66, capacity: 984, estimated: true },
  { ward: '練馬区', fiscal_year: 2024, category: '認可保育所', count: 195, capacity: 17547, estimated: false },
  { ward: '練馬区', fiscal_year: 2024, category: '認定こども園', count: 1, capacity: 196, estimated: false },
  { ward: '練馬区', fiscal_year: 2024, category: '小規模保育等', count: 70, capacity: 1043, estimated: false },
  { ward: '足立区', fiscal_year: 2020, category: '認可保育所', count: 136, capacity: 12274, estimated: true },
  { ward: '足立区', fiscal_year: 2020, category: '認定こども園', count: 1, capacity: 212, estimated: true },
  { ward: '足立区', fiscal_year: 2020, category: '小規模保育等', count: 42, capacity: 623, estimated: true },
  { ward: '足立区', fiscal_year: 2021, category: '認可保育所', count: 140, capacity: 12643, estimated: true },
  { ward: '足立区', fiscal_year: 2021, category: '認定こども園', count: 2, capacity: 244, estimated: true },
  { ward: '足立区', fiscal_year: 2021, category: '小規模保育等', count: 44, capacity: 661, estimated: true },
  { ward: '足立区', fiscal_year: 2022, category: '認可保育所', count: 145, capacity: 13022, estimated: true },
  { ward: '足立区', fiscal_year: 2022, category: '認定こども園', count: 2, capacity: 281, estimated: true },
  { ward: '足立区', fiscal_year: 2022, category: '小規模保育等', count: 47, capacity: 700, estimated: true },
  { ward: '足立区', fiscal_year: 2023, category: '認可保育所', count: 149, capacity: 13413, estimated: true },
  { ward: '足立区', fiscal_year: 2023, category: '認定こども園', count: 2, capacity: 323, estimated: true },
  { ward: '足立区', fiscal_year: 2023, category: '小規模保育等', count: 49, capacity: 742, estimated: true },
  { ward: '足立区', fiscal_year: 2024, category: '認可保育所', count: 154, capacity: 13815, estimated: false },
  { ward: '足立区', fiscal_year: 2024, category: '認定こども園', count: 2, capacity: 371, estimated: false },
  { ward: '足立区', fiscal_year: 2024, category: '小規模保育等', count: 52, capacity: 787, estimated: false },
  { ward: '葛飾区', fiscal_year: 2020, category: '認可保育所', count: 113, capacity: 10163, estimated: true },
  { ward: '葛飾区', fiscal_year: 2020, category: '認定こども園', count: 3, capacity: 382, estimated: true },
  { ward: '葛飾区', fiscal_year: 2020, category: '小規模保育等', count: 17, capacity: 261, estimated: true },
  { ward: '葛飾区', fiscal_year: 2021, category: '認可保育所', count: 116, capacity: 10468, estimated: true },
  { ward: '葛飾区', fiscal_year: 2021, category: '認定こども園', count: 3, capacity: 439, estimated: true },
  { ward: '葛飾区', fiscal_year: 2021, category: '小規模保育等', count: 18, capacity: 276, estimated: true },
  { ward: '葛飾区', fiscal_year: 2022, category: '認可保育所', count: 120, capacity: 10782, estimated: true },
  { ward: '葛飾区', fiscal_year: 2022, category: '認定こども園', count: 3, capacity: 505, estimated: true },
  { ward: '葛飾区', fiscal_year: 2022, category: '小規模保育等', count: 20, capacity: 293, estimated: true },
  { ward: '葛飾区', fiscal_year: 2023, category: '認可保育所', count: 123, capacity: 11106, estimated: true },
  { ward: '葛飾区', fiscal_year: 2023, category: '認定こども園', count: 4, capacity: 581, estimated: true },
  { ward: '葛飾区', fiscal_year: 2023, category: '小規模保育等', count: 21, capacity: 310, estimated: true },
  { ward: '葛飾区', fiscal_year: 2024, category: '認可保育所', count: 127, capacity: 11439, estimated: false },
  { ward: '葛飾区', fiscal_year: 2024, category: '認定こども園', count: 4, capacity: 668, estimated: false },
  { ward: '葛飾区', fiscal_year: 2024, category: '小規模保育等', count: 22, capacity: 329, estimated: false },
  { ward: '江戸川区', fiscal_year: 2020, category: '認可保育所', count: 143, capacity: 12892, estimated: true },
  { ward: '江戸川区', fiscal_year: 2020, category: '認定こども園', count: 3, capacity: 467, estimated: true },
  { ward: '江戸川区', fiscal_year: 2020, category: '小規模保育等', count: 19, capacity: 280, estimated: true },
  { ward: '江戸川区', fiscal_year: 2021, category: '認可保育所', count: 148, capacity: 13279, estimated: true },
  { ward: '江戸川区', fiscal_year: 2021, category: '認定こども園', count: 4, capacity: 537, estimated: true },
  { ward: '江戸川区', fiscal_year: 2021, category: '小規模保育等', count: 20, capacity: 296, estimated: true },
  { ward: '江戸川区', fiscal_year: 2022, category: '認可保育所', count: 152, capacity: 13677, estimated: true },
  { ward: '江戸川区', fiscal_year: 2022, category: '認定こども園', count: 4, capacity: 618, estimated: true },
  { ward: '江戸川区', fiscal_year: 2022, category: '小規模保育等', count: 21, capacity: 314, estimated: true },
  { ward: '江戸川区', fiscal_year: 2023, category: '認可保育所', count: 157, capacity: 14087, estimated: true },
  { ward: '江戸川区', fiscal_year: 2023, category: '認定こども園', count: 5, capacity: 710, estimated: true },
  { ward: '江戸川区', fiscal_year: 2023, category: '小規模保育等', count: 22, capacity: 333, estimated: true },
  { ward: '江戸川区', fiscal_year: 2024, category: '認可保育所', count: 161, capacity: 14510, estimated: false },
  { ward: '江戸川区', fiscal_year: 2024, category: '認定こども園', count: 5, capacity: 817, estimated: false },
  { ward: '江戸川区', fiscal_year: 2024, category: '小規模保育等', count: 24, capacity: 353, estimated: false },
]

export const SEED_WAITING: SeedWaiting[] = [
  { ward: '千代田区', fiscal_year: 2020, total_waiting: 0, total_hidden_waiting: null },
  { ward: '中央区', fiscal_year: 2020, total_waiting: 202, total_hidden_waiting: null },
  { ward: '港区', fiscal_year: 2020, total_waiting: 0, total_hidden_waiting: null },
  { ward: '新宿区', fiscal_year: 2020, total_waiting: 1, total_hidden_waiting: null },
  { ward: '文京区', fiscal_year: 2020, total_waiting: 11, total_hidden_waiting: null },
  { ward: '台東区', fiscal_year: 2020, total_waiting: 60, total_hidden_waiting: null },
  { ward: '墨田区', fiscal_year: 2020, total_waiting: 97, total_hidden_waiting: null },
  { ward: '江東区', fiscal_year: 2020, total_waiting: 14, total_hidden_waiting: null },
  { ward: '品川区', fiscal_year: 2020, total_waiting: 13, total_hidden_waiting: null },
  { ward: '目黒区', fiscal_year: 2020, total_waiting: 0, total_hidden_waiting: null },
  { ward: '大田区', fiscal_year: 2020, total_waiting: 35, total_hidden_waiting: null },
  { ward: '世田谷区', fiscal_year: 2020, total_waiting: 0, total_hidden_waiting: null },
  { ward: '渋谷区', fiscal_year: 2020, total_waiting: 58, total_hidden_waiting: null },
  { ward: '中野区', fiscal_year: 2020, total_waiting: 73, total_hidden_waiting: null },
  { ward: '杉並区', fiscal_year: 2020, total_waiting: 0, total_hidden_waiting: null },
  { ward: '豊島区', fiscal_year: 2020, total_waiting: 0, total_hidden_waiting: null },
  { ward: '北区', fiscal_year: 2020, total_waiting: 79, total_hidden_waiting: null },
  { ward: '荒川区', fiscal_year: 2020, total_waiting: 28, total_hidden_waiting: null },
  { ward: '板橋区', fiscal_year: 2020, total_waiting: 80, total_hidden_waiting: null },
  { ward: '練馬区', fiscal_year: 2020, total_waiting: 11, total_hidden_waiting: null },
  { ward: '足立区', fiscal_year: 2020, total_waiting: 3, total_hidden_waiting: null },
  { ward: '葛飾区', fiscal_year: 2020, total_waiting: 21, total_hidden_waiting: null },
  { ward: '江戸川区', fiscal_year: 2020, total_waiting: 203, total_hidden_waiting: null },
  { ward: '千代田区', fiscal_year: 2021, total_waiting: 0, total_hidden_waiting: null },
  { ward: '中央区', fiscal_year: 2021, total_waiting: 85, total_hidden_waiting: null },
  { ward: '港区', fiscal_year: 2021, total_waiting: 0, total_hidden_waiting: null },
  { ward: '新宿区', fiscal_year: 2021, total_waiting: 0, total_hidden_waiting: null },
  { ward: '文京区', fiscal_year: 2021, total_waiting: 1, total_hidden_waiting: null },
  { ward: '台東区', fiscal_year: 2021, total_waiting: 15, total_hidden_waiting: null },
  { ward: '墨田区', fiscal_year: 2021, total_waiting: 29, total_hidden_waiting: null },
  { ward: '江東区', fiscal_year: 2021, total_waiting: 4, total_hidden_waiting: null },
  { ward: '品川区', fiscal_year: 2021, total_waiting: 5, total_hidden_waiting: null },
  { ward: '目黒区', fiscal_year: 2021, total_waiting: 0, total_hidden_waiting: null },
  { ward: '大田区', fiscal_year: 2021, total_waiting: 0, total_hidden_waiting: null },
  { ward: '世田谷区', fiscal_year: 2021, total_waiting: 0, total_hidden_waiting: null },
  { ward: '渋谷区', fiscal_year: 2021, total_waiting: 0, total_hidden_waiting: null },
  { ward: '中野区', fiscal_year: 2021, total_waiting: 25, total_hidden_waiting: null },
  { ward: '杉並区', fiscal_year: 2021, total_waiting: 0, total_hidden_waiting: null },
  { ward: '豊島区', fiscal_year: 2021, total_waiting: 0, total_hidden_waiting: null },
  { ward: '北区', fiscal_year: 2021, total_waiting: 18, total_hidden_waiting: null },
  { ward: '荒川区', fiscal_year: 2021, total_waiting: 21, total_hidden_waiting: null },
  { ward: '板橋区', fiscal_year: 2021, total_waiting: 36, total_hidden_waiting: null },
  { ward: '練馬区', fiscal_year: 2021, total_waiting: 0, total_hidden_waiting: null },
  { ward: '足立区', fiscal_year: 2021, total_waiting: 0, total_hidden_waiting: null },
  { ward: '葛飾区', fiscal_year: 2021, total_waiting: 0, total_hidden_waiting: null },
  { ward: '江戸川区', fiscal_year: 2021, total_waiting: 49, total_hidden_waiting: null },
  { ward: '千代田区', fiscal_year: 2022, total_waiting: 0, total_hidden_waiting: null },
  { ward: '中央区', fiscal_year: 2022, total_waiting: 0, total_hidden_waiting: null },
  { ward: '港区', fiscal_year: 2022, total_waiting: 0, total_hidden_waiting: null },
  { ward: '新宿区', fiscal_year: 2022, total_waiting: 0, total_hidden_waiting: null },
  { ward: '文京区', fiscal_year: 2022, total_waiting: 2, total_hidden_waiting: null },
  { ward: '台東区', fiscal_year: 2022, total_waiting: 6, total_hidden_waiting: null },
  { ward: '墨田区', fiscal_year: 2022, total_waiting: 7, total_hidden_waiting: null },
  { ward: '江東区', fiscal_year: 2022, total_waiting: 0, total_hidden_waiting: null },
  { ward: '品川区', fiscal_year: 2022, total_waiting: 0, total_hidden_waiting: null },
  { ward: '目黒区', fiscal_year: 2022, total_waiting: 0, total_hidden_waiting: null },
  { ward: '大田区', fiscal_year: 2022, total_waiting: 0, total_hidden_waiting: null },
  { ward: '世田谷区', fiscal_year: 2022, total_waiting: 0, total_hidden_waiting: null },
  { ward: '渋谷区', fiscal_year: 2022, total_waiting: 0, total_hidden_waiting: null },
  { ward: '中野区', fiscal_year: 2022, total_waiting: 0, total_hidden_waiting: null },
  { ward: '杉並区', fiscal_year: 2022, total_waiting: 0, total_hidden_waiting: null },
  { ward: '豊島区', fiscal_year: 2022, total_waiting: 0, total_hidden_waiting: null },
  { ward: '北区', fiscal_year: 2022, total_waiting: 16, total_hidden_waiting: null },
  { ward: '荒川区', fiscal_year: 2022, total_waiting: 0, total_hidden_waiting: null },
  { ward: '板橋区', fiscal_year: 2022, total_waiting: 0, total_hidden_waiting: null },
  { ward: '練馬区', fiscal_year: 2022, total_waiting: 0, total_hidden_waiting: null },
  { ward: '足立区', fiscal_year: 2022, total_waiting: 1, total_hidden_waiting: null },
  { ward: '葛飾区', fiscal_year: 2022, total_waiting: 0, total_hidden_waiting: null },
  { ward: '江戸川区', fiscal_year: 2022, total_waiting: 0, total_hidden_waiting: null },
  { ward: '千代田区', fiscal_year: 2023, total_waiting: 0, total_hidden_waiting: null },
  { ward: '中央区', fiscal_year: 2023, total_waiting: 0, total_hidden_waiting: null },
  { ward: '港区', fiscal_year: 2023, total_waiting: 0, total_hidden_waiting: null },
  { ward: '新宿区', fiscal_year: 2023, total_waiting: 0, total_hidden_waiting: null },
  { ward: '文京区', fiscal_year: 2023, total_waiting: 0, total_hidden_waiting: null },
  { ward: '台東区', fiscal_year: 2023, total_waiting: 0, total_hidden_waiting: null },
  { ward: '墨田区', fiscal_year: 2023, total_waiting: 2, total_hidden_waiting: null },
  { ward: '江東区', fiscal_year: 2023, total_waiting: 0, total_hidden_waiting: null },
  { ward: '品川区', fiscal_year: 2023, total_waiting: 0, total_hidden_waiting: null },
  { ward: '目黒区', fiscal_year: 2023, total_waiting: 0, total_hidden_waiting: null },
  { ward: '大田区', fiscal_year: 2023, total_waiting: 0, total_hidden_waiting: null },
  { ward: '世田谷区', fiscal_year: 2023, total_waiting: 10, total_hidden_waiting: null },
  { ward: '渋谷区', fiscal_year: 2023, total_waiting: 0, total_hidden_waiting: null },
  { ward: '中野区', fiscal_year: 2023, total_waiting: 0, total_hidden_waiting: null },
  { ward: '杉並区', fiscal_year: 2023, total_waiting: 0, total_hidden_waiting: null },
  { ward: '豊島区', fiscal_year: 2023, total_waiting: 0, total_hidden_waiting: null },
  { ward: '北区', fiscal_year: 2023, total_waiting: 0, total_hidden_waiting: null },
  { ward: '荒川区', fiscal_year: 2023, total_waiting: 0, total_hidden_waiting: null },
  { ward: '板橋区', fiscal_year: 2023, total_waiting: 0, total_hidden_waiting: null },
  { ward: '練馬区', fiscal_year: 2023, total_waiting: 0, total_hidden_waiting: null },
  { ward: '足立区', fiscal_year: 2023, total_waiting: 0, total_hidden_waiting: null },
  { ward: '葛飾区', fiscal_year: 2023, total_waiting: 0, total_hidden_waiting: null },
  { ward: '江戸川区', fiscal_year: 2023, total_waiting: 0, total_hidden_waiting: null },
  { ward: '千代田区', fiscal_year: 2024, total_waiting: 0, total_hidden_waiting: null },
  { ward: '中央区', fiscal_year: 2024, total_waiting: 0, total_hidden_waiting: null },
  { ward: '港区', fiscal_year: 2024, total_waiting: 0, total_hidden_waiting: null },
  { ward: '新宿区', fiscal_year: 2024, total_waiting: 0, total_hidden_waiting: null },
  { ward: '文京区', fiscal_year: 2024, total_waiting: 2, total_hidden_waiting: null },
  { ward: '台東区', fiscal_year: 2024, total_waiting: 0, total_hidden_waiting: null },
  { ward: '墨田区', fiscal_year: 2024, total_waiting: 8, total_hidden_waiting: null },
  { ward: '江東区', fiscal_year: 2024, total_waiting: 0, total_hidden_waiting: null },
  { ward: '品川区', fiscal_year: 2024, total_waiting: 0, total_hidden_waiting: null },
  { ward: '目黒区', fiscal_year: 2024, total_waiting: 0, total_hidden_waiting: null },
  { ward: '大田区', fiscal_year: 2024, total_waiting: 0, total_hidden_waiting: null },
  { ward: '世田谷区', fiscal_year: 2024, total_waiting: 58, total_hidden_waiting: null },
  { ward: '渋谷区', fiscal_year: 2024, total_waiting: 0, total_hidden_waiting: null },
  { ward: '中野区', fiscal_year: 2024, total_waiting: 0, total_hidden_waiting: null },
  { ward: '杉並区', fiscal_year: 2024, total_waiting: 0, total_hidden_waiting: null },
  { ward: '豊島区', fiscal_year: 2024, total_waiting: 0, total_hidden_waiting: null },
  { ward: '北区', fiscal_year: 2024, total_waiting: 8, total_hidden_waiting: null },
  { ward: '荒川区', fiscal_year: 2024, total_waiting: 33, total_hidden_waiting: null },
  { ward: '板橋区', fiscal_year: 2024, total_waiting: 0, total_hidden_waiting: null },
  { ward: '練馬区', fiscal_year: 2024, total_waiting: 0, total_hidden_waiting: null },
  { ward: '足立区', fiscal_year: 2024, total_waiting: 5, total_hidden_waiting: null },
  { ward: '葛飾区', fiscal_year: 2024, total_waiting: 0, total_hidden_waiting: null },
  { ward: '江戸川区', fiscal_year: 2024, total_waiting: 0, total_hidden_waiting: null },
]

export const SEED_BIRTHS: SeedBirth[] = [
  { ward: '千代田区', fiscal_year: 2020, birth_count: 673 },
  { ward: '中央区', fiscal_year: 2020, birth_count: 2144 },
  { ward: '港区', fiscal_year: 2020, birth_count: 2817 },
  { ward: '新宿区', fiscal_year: 2020, birth_count: 2591 },
  { ward: '文京区', fiscal_year: 2020, birth_count: 2109 },
  { ward: '台東区', fiscal_year: 2020, birth_count: 1612 },
  { ward: '墨田区', fiscal_year: 2020, birth_count: 2370 },
  { ward: '江東区', fiscal_year: 2020, birth_count: 4325 },
  { ward: '品川区', fiscal_year: 2020, birth_count: 3845 },
  { ward: '目黒区', fiscal_year: 2020, birth_count: 2353 },
  { ward: '大田区', fiscal_year: 2020, birth_count: 5672 },
  { ward: '世田谷区', fiscal_year: 2020, birth_count: 6845 },
  { ward: '渋谷区', fiscal_year: 2020, birth_count: 2016 },
  { ward: '中野区', fiscal_year: 2020, birth_count: 2530 },
  { ward: '杉並区', fiscal_year: 2020, birth_count: 4454 },
  { ward: '豊島区', fiscal_year: 2020, birth_count: 2036 },
  { ward: '北区', fiscal_year: 2020, birth_count: 2872 },
  { ward: '荒川区', fiscal_year: 2020, birth_count: 1753 },
  { ward: '板橋区', fiscal_year: 2020, birth_count: 4089 },
  { ward: '練馬区', fiscal_year: 2020, birth_count: 5515 },
  { ward: '足立区', fiscal_year: 2020, birth_count: 4686 },
  { ward: '葛飾区', fiscal_year: 2020, birth_count: 3392 },
  { ward: '江戸川区', fiscal_year: 2020, birth_count: 5287 },
  { ward: '千代田区', fiscal_year: 2021, birth_count: 616 },
  { ward: '中央区', fiscal_year: 2021, birth_count: 2010 },
  { ward: '港区', fiscal_year: 2021, birth_count: 2595 },
  { ward: '新宿区', fiscal_year: 2021, birth_count: 2465 },
  { ward: '文京区', fiscal_year: 2021, birth_count: 1884 },
  { ward: '台東区', fiscal_year: 2021, birth_count: 1570 },
  { ward: '墨田区', fiscal_year: 2021, birth_count: 2295 },
  { ward: '江東区', fiscal_year: 2021, birth_count: 4206 },
  { ward: '品川区', fiscal_year: 2021, birth_count: 3632 },
  { ward: '目黒区', fiscal_year: 2021, birth_count: 2159 },
  { ward: '大田区', fiscal_year: 2021, birth_count: 5344 },
  { ward: '世田谷区', fiscal_year: 2021, birth_count: 6818 },
  { ward: '渋谷区', fiscal_year: 2021, birth_count: 1956 },
  { ward: '中野区', fiscal_year: 2021, birth_count: 2481 },
  { ward: '杉並区', fiscal_year: 2021, birth_count: 4186 },
  { ward: '豊島区', fiscal_year: 2021, birth_count: 2013 },
  { ward: '北区', fiscal_year: 2021, birth_count: 2690 },
  { ward: '荒川区', fiscal_year: 2021, birth_count: 1692 },
  { ward: '板橋区', fiscal_year: 2021, birth_count: 3836 },
  { ward: '練馬区', fiscal_year: 2021, birth_count: 5341 },
  { ward: '足立区', fiscal_year: 2021, birth_count: 4323 },
  { ward: '葛飾区', fiscal_year: 2021, birth_count: 3079 },
  { ward: '江戸川区', fiscal_year: 2021, birth_count: 4985 },
  { ward: '千代田区', fiscal_year: 2022, birth_count: 585 },
  { ward: '中央区', fiscal_year: 2022, birth_count: 1940 },
  { ward: '港区', fiscal_year: 2022, birth_count: 2436 },
  { ward: '新宿区', fiscal_year: 2022, birth_count: 2328 },
  { ward: '文京区', fiscal_year: 2022, birth_count: 1845 },
  { ward: '台東区', fiscal_year: 2022, birth_count: 1463 },
  { ward: '墨田区', fiscal_year: 2022, birth_count: 2152 },
  { ward: '江東区', fiscal_year: 2022, birth_count: 3876 },
  { ward: '品川区', fiscal_year: 2022, birth_count: 3460 },
  { ward: '目黒区', fiscal_year: 2022, birth_count: 2179 },
  { ward: '大田区', fiscal_year: 2022, birth_count: 5068 },
  { ward: '世田谷区', fiscal_year: 2022, birth_count: 6326 },
  { ward: '渋谷区', fiscal_year: 2022, birth_count: 1802 },
  { ward: '中野区', fiscal_year: 2022, birth_count: 2334 },
  { ward: '杉並区', fiscal_year: 2022, birth_count: 4030 },
  { ward: '豊島区', fiscal_year: 2022, birth_count: 1982 },
  { ward: '北区', fiscal_year: 2022, birth_count: 2562 },
  { ward: '荒川区', fiscal_year: 2022, birth_count: 1624 },
  { ward: '板橋区', fiscal_year: 2022, birth_count: 3605 },
  { ward: '練馬区', fiscal_year: 2022, birth_count: 5217 },
  { ward: '足立区', fiscal_year: 2022, birth_count: 4188 },
  { ward: '葛飾区', fiscal_year: 2022, birth_count: 3091 },
  { ward: '江戸川区', fiscal_year: 2022, birth_count: 4719 },
  { ward: '千代田区', fiscal_year: 2023, birth_count: 596 },
  { ward: '中央区', fiscal_year: 2023, birth_count: 1813 },
  { ward: '港区', fiscal_year: 2023, birth_count: 2519 },
  { ward: '新宿区', fiscal_year: 2023, birth_count: 2153 },
  { ward: '文京区', fiscal_year: 2023, birth_count: 1874 },
  { ward: '台東区', fiscal_year: 2023, birth_count: 1476 },
  { ward: '墨田区', fiscal_year: 2023, birth_count: 2189 },
  { ward: '江東区', fiscal_year: 2023, birth_count: 3824 },
  { ward: '品川区', fiscal_year: 2023, birth_count: 3183 },
  { ward: '目黒区', fiscal_year: 2023, birth_count: 2008 },
  { ward: '大田区', fiscal_year: 2023, birth_count: 4743 },
  { ward: '世田谷区', fiscal_year: 2023, birth_count: 6011 },
  { ward: '渋谷区', fiscal_year: 2023, birth_count: 1675 },
  { ward: '中野区', fiscal_year: 2023, birth_count: 2238 },
  { ward: '杉並区', fiscal_year: 2023, birth_count: 3788 },
  { ward: '豊島区', fiscal_year: 2023, birth_count: 1854 },
  { ward: '北区', fiscal_year: 2023, birth_count: 2441 },
  { ward: '荒川区', fiscal_year: 2023, birth_count: 1576 },
  { ward: '板橋区', fiscal_year: 2023, birth_count: 3412 },
  { ward: '練馬区', fiscal_year: 2023, birth_count: 4988 },
  { ward: '足立区', fiscal_year: 2023, birth_count: 4031 },
  { ward: '葛飾区', fiscal_year: 2023, birth_count: 2823 },
  { ward: '江戸川区', fiscal_year: 2023, birth_count: 4465 },
  { ward: '千代田区', fiscal_year: 2024, birth_count: 547 },
  { ward: '中央区', fiscal_year: 2024, birth_count: 1955 },
  { ward: '港区', fiscal_year: 2024, birth_count: 2412 },
  { ward: '新宿区', fiscal_year: 2024, birth_count: 2107 },
  { ward: '文京区', fiscal_year: 2024, birth_count: 1796 },
  { ward: '台東区', fiscal_year: 2024, birth_count: 1567 },
  { ward: '墨田区', fiscal_year: 2024, birth_count: 2147 },
  { ward: '江東区', fiscal_year: 2024, birth_count: 3732 },
  { ward: '品川区', fiscal_year: 2024, birth_count: 3119 },
  { ward: '目黒区', fiscal_year: 2024, birth_count: 2011 },
  { ward: '大田区', fiscal_year: 2024, birth_count: 4670 },
  { ward: '世田谷区', fiscal_year: 2024, birth_count: 6000 },
  { ward: '渋谷区', fiscal_year: 2024, birth_count: 1669 },
  { ward: '中野区', fiscal_year: 2024, birth_count: 2188 },
  { ward: '杉並区', fiscal_year: 2024, birth_count: 3582 },
  { ward: '豊島区', fiscal_year: 2024, birth_count: 1814 },
  { ward: '北区', fiscal_year: 2024, birth_count: 2518 },
  { ward: '荒川区', fiscal_year: 2024, birth_count: 1478 },
  { ward: '板橋区', fiscal_year: 2024, birth_count: 3406 },
  { ward: '練馬区', fiscal_year: 2024, birth_count: 4876 },
  { ward: '足立区', fiscal_year: 2024, birth_count: 4120 },
  { ward: '葛飾区', fiscal_year: 2024, birth_count: 2952 },
  { ward: '江戸川区', fiscal_year: 2024, birth_count: 4516 },
]