// =============================================
// 新築マンション seed データ（Phase M）
// 月次更新: Claude に依頼してスクレイピング → このファイルを更新
// 最終更新: 2026-04-18（座標: Nominatim API による住所ジオコード済み）
// =============================================

export type MansionStatus = '建築予定' | '建築中' | '分譲中'

export interface MansionRecord {
  id:              string
  name:            string
  developers:      string[]
  ward:            string
  address:         string
  lat:             number
  lng:             number
  status:          MansionStatus
  floors:          number | null
  total_units:     number | null
  site_area:       number | null
  area_min:        number | null
  area_max:        number | null
  completion:      string | null
  delivery:        string | null
  constructor:     string | null
  parking:         string | null
  bicycle_parking: number | null
  ceiling_height:  string | null
  floor_method:    string | null
  disposer:        boolean | null
  eco_type:        string | null
  corridor:        '内廊下' | '外廊下' | null
  url:             string
  updated_at:      string
}

export const SEED_MANSIONS: MansionRecord[] = [
  {
    id:              "proud-bunkyo-honkomagome",
    name:            "プラウド文京本駒込",
    developers:      ["野村不動産"],
    ward:            "文京区",
    address:         "文京区本駒込",
    lat:             35.7337898,
    lng:             139.7518046,
    status:          "分譲中",
    floors:          null,
    total_units:     62,
    site_area:       null,
    area_min:        63.11,
    area_max:        94.57,
    completion:      null,
    delivery:        null,
    constructor:     null,
    parking:         null,
    bicycle_parking: null,
    ceiling_height:  null,
    floor_method:    null,
    disposer:        null,
    eco_type:        null,
    corridor:        null,
    url:             "https://www.proud-web.jp/search/kanto/",
    updated_at:      "2026-04-18",
  },
  {
    id:              "proud-shinjuku-yotsuya",
    name:            "プラウド四谷",
    developers:      ["野村不動産"],
    ward:            "新宿区",
    address:         "新宿区四谷",
    lat:             35.6857312,
    lng:             139.7299067,
    status:          "分譲中",
    floors:          null,
    total_units:     38,
    site_area:       null,
    area_min:        70.07,
    area_max:        84.42,
    completion:      null,
    delivery:        null,
    constructor:     null,
    parking:         null,
    bicycle_parking: null,
    ceiling_height:  null,
    floor_method:    null,
    disposer:        null,
    eco_type:        null,
    corridor:        null,
    url:             "https://www.proud-web.jp/search/kanto/",
    updated_at:      "2026-04-18",
  },
  {
    id:              "proud-meguro-jiyugaoka-hilltop",
    name:            "プラウド自由が丘ヒルトップ",
    developers:      ["野村不動産"],
    ward:            "目黒区",
    address:         "目黒区自由が丘",
    lat:             35.6103751,
    lng:             139.6735317,
    status:          "分譲中",
    floors:          null,
    total_units:     31,
    site_area:       null,
    area_min:        76.39,
    area_max:        114.62,
    completion:      null,
    delivery:        null,
    constructor:     null,
    parking:         null,
    bicycle_parking: null,
    ceiling_height:  null,
    floor_method:    null,
    disposer:        null,
    eco_type:        null,
    corridor:        null,
    url:             "https://www.proud-web.jp/search/kanto/",
    updated_at:      "2026-04-18",
  },
  {
    id:              "proud-tower-kita-akabane",
    name:            "プラウドタワー赤羽",
    developers:      ["野村不動産"],
    ward:            "北区",
    address:         "北区赤羽",
    lat:             35.7783,
    lng:             139.7196,
    status:          "分譲中",
    floors:          null,
    total_units:     325,
    site_area:       null,
    area_min:        35.28,
    area_max:        127.06,
    completion:      null,
    delivery:        null,
    constructor:     null,
    parking:         null,
    bicycle_parking: null,
    ceiling_height:  null,
    floor_method:    null,
    disposer:        null,
    eco_type:        null,
    corridor:        null,
    url:             "https://www.proud-web.jp/search/kanto/",
    updated_at:      "2026-04-18",
  },
  {
    id:              "proud-tower-toshima-ikebukuro",
    name:            "プラウドタワー池袋",
    developers:      ["野村不動産"],
    ward:            "豊島区",
    address:         "豊島区南池袋",
    lat:             35.7226083,
    lng:             139.7181732,
    status:          "分譲中",
    floors:          null,
    total_units:     620,
    site_area:       null,
    area_min:        31.24,
    area_max:        143.76,
    completion:      null,
    delivery:        null,
    constructor:     null,
    parking:         null,
    bicycle_parking: null,
    ceiling_height:  null,
    floor_method:    null,
    disposer:        null,
    eco_type:        null,
    corridor:        null,
    url:             "https://www.proud-web.jp/search/kanto/",
    updated_at:      "2026-04-18",
  },
  {
    id:              "brillia-taito-matsugaya",
    name:            "Brillia 上野松が谷 The Residence",
    developers:      ["東京建物"],
    ward:            "台東区",
    address:         "台東区松が谷2丁目",
    lat:             35.7155447,
    lng:             139.7836602,
    status:          "分譲中",
    floors:          null,
    total_units:     26,
    site_area:       null,
    area_min:        54.68,
    area_max:        54.74,
    completion:      null,
    delivery:        null,
    constructor:     null,
    parking:         null,
    bicycle_parking: null,
    ceiling_height:  null,
    floor_method:    null,
    disposer:        null,
    eco_type:        null,
    corridor:        null,
    url:             "https://brillia.com/re/search-area/matsugaya26.index.html",
    updated_at:      "2026-04-18",
  },
  {
    id:              "brillia-tower-asakusa-yanagibashi",
    name:            "Brillia Tower 浅草柳橋",
    developers:      ["東京建物"],
    ward:            "台東区",
    address:         "台東区柳橋2丁目",
    lat:             35.7002349,
    lng:             139.7913319,
    status:          "分譲中",
    floors:          null,
    total_units:     267,
    site_area:       null,
    area_min:        33.15,
    area_max:        104.3,
    completion:      null,
    delivery:        null,
    constructor:     null,
    parking:         null,
    bicycle_parking: null,
    ceiling_height:  null,
    floor_method:    null,
    disposer:        null,
    eco_type:        null,
    corridor:        null,
    url:             "https://brillia.com/re/search-area/bta.index.html",
    updated_at:      "2026-04-18",
  },
  {
    id:              "brillia-shinjuku-nishishinjuku",
    name:            "Brillia 西新宿",
    developers:      ["東京建物"],
    ward:            "新宿区",
    address:         "新宿区西新宿8丁目",
    lat:             35.6957772,
    lng:             139.6947458,
    status:          "分譲中",
    floors:          null,
    total_units:     71,
    site_area:       null,
    area_min:        31.02,
    area_max:        93.09,
    completion:      null,
    delivery:        null,
    constructor:     null,
    parking:         null,
    bicycle_parking: null,
    ceiling_height:  null,
    floor_method:    null,
    disposer:        null,
    eco_type:        null,
    corridor:        null,
    url:             "https://brillia.com/re/search-area/bn5.index.html",
    updated_at:      "2026-04-18",
  },
  {
    id:              "brillia-nakano-hounanchou",
    name:            "Brillia 方南町",
    developers:      ["東京建物"],
    ward:            "中野区",
    address:         "中野区南台5丁目",
    lat:             35.684413,
    lng:             139.6628944,
    status:          "分譲中",
    floors:          null,
    total_units:     179,
    site_area:       null,
    area_min:        43.58,
    area_max:        85.86,
    completion:      null,
    delivery:        null,
    constructor:     null,
    parking:         null,
    bicycle_parking: null,
    ceiling_height:  null,
    floor_method:    null,
    disposer:        null,
    eco_type:        null,
    corridor:        null,
    url:             "https://brillia.com/re/search-area/hounanchou179.index.html",
    updated_at:      "2026-04-18",
  },
  {
    id:              "brillia-arakawa-machiya",
    name:            "Brillia 町屋",
    developers:      ["東京建物"],
    ward:            "荒川区",
    address:         "荒川区町屋2丁目",
    lat:             35.7449928,
    lng:             139.7802583,
    status:          "分譲中",
    floors:          null,
    total_units:     40,
    site_area:       null,
    area_min:        53.31,
    area_max:        82.31,
    completion:      null,
    delivery:        null,
    constructor:     null,
    parking:         null,
    bicycle_parking: null,
    ceiling_height:  null,
    floor_method:    null,
    disposer:        null,
    eco_type:        null,
    corridor:        null,
    url:             "https://brillia.com/re/search-area/machiya.index.html",
    updated_at:      "2026-04-18",
  },
  {
    id:              "brillia-shinjuku-waseda-tsurumaki",
    name:            "Brillia 早稲田鶴巻町",
    developers:      ["東京建物"],
    ward:            "新宿区",
    address:         "新宿区早稲田鶴巻町",
    lat:             35.7067623,
    lng:             139.7282444,
    status:          "分譲中",
    floors:          null,
    total_units:     30,
    site_area:       null,
    area_min:        35.04,
    area_max:        70.4,
    completion:      null,
    delivery:        null,
    constructor:     null,
    parking:         null,
    bicycle_parking: null,
    ceiling_height:  null,
    floor_method:    null,
    disposer:        null,
    eco_type:        null,
    corridor:        null,
    url:             "https://brillia.com/re/search-area/bwt3.index.html",
    updated_at:      "2026-04-18",
  },
  {
    id:              "brillia-tower-minato-nogizaka",
    name:            "Brillia Tower 乃木坂",
    developers:      ["東京建物"],
    ward:            "港区",
    address:         "港区南青山1丁目",
    lat:             35.6738338,
    lng:             139.7226384,
    status:          "分譲中",
    floors:          null,
    total_units:     102,
    site_area:       null,
    area_min:        65.32,
    area_max:        120.97,
    completion:      null,
    delivery:        null,
    constructor:     null,
    parking:         null,
    bicycle_parking: null,
    ceiling_height:  null,
    floor_method:    null,
    disposer:        null,
    eco_type:        null,
    corridor:        null,
    url:             "https://brillia.com/re/search-area/nogizaka-tower.index.html",
    updated_at:      "2026-04-18",
  },
  {
    id:              "brillia-bunkyo-nishikata",
    name:            "Brillia 文京西片",
    developers:      ["東京建物"],
    ward:            "文京区",
    address:         "文京区西片2丁目",
    lat:             35.7174745,
    lng:             139.7539504,
    status:          "分譲中",
    floors:          null,
    total_units:     18,
    site_area:       null,
    area_min:        55.99,
    area_max:        71.77,
    completion:      null,
    delivery:        null,
    constructor:     null,
    parking:         null,
    bicycle_parking: null,
    ceiling_height:  null,
    floor_method:    null,
    disposer:        null,
    eco_type:        null,
    corridor:        null,
    url:             "https://brillia.com/re/search-area/nishikata.index.html",
    updated_at:      "2026-04-18",
  },
  {
    id:              "brillia-setagaya-kamikitazawa",
    name:            "Brillia 世田谷上北沢",
    developers:      ["東京建物"],
    ward:            "世田谷区",
    address:         "世田谷区上北沢5丁目",
    lat:             35.6737326,
    lng:             139.6135339,
    status:          "分譲中",
    floors:          null,
    total_units:     86,
    site_area:       null,
    area_min:        34.77,
    area_max:        85.12,
    completion:      null,
    delivery:        null,
    constructor:     null,
    parking:         null,
    bicycle_parking: null,
    ceiling_height:  null,
    floor_method:    null,
    disposer:        null,
    eco_type:        null,
    corridor:        null,
    url:             "https://brillia.com/re/search-area/kamikita86.index.html",
    updated_at:      "2026-04-18",
  },
  {
    id:              "tph-chiyoda-sanbancho-residence",
    name:            "ザ レジデンス 三番町",
    developers:      ["三菱地所レジデンス", "東京建物"],
    ward:            "千代田区",
    address:         "千代田区三番町",
    lat:             35.6903981,
    lng:             139.7408723,
    status:          "分譲中",
    floors:          18,
    total_units:     124,
    site_area:       null,
    area_min:        56.9,
    area_max:        142.54,
    completion:      null,
    delivery:        null,
    constructor:     null,
    parking:         null,
    bicycle_parking: null,
    ceiling_height:  null,
    floor_method:    null,
    disposer:        null,
    eco_type:        null,
    corridor:        null,
    url:             "https://www.mecsumai.com/tr-sanbancho/",
    updated_at:      "2026-04-18",
  },
  {
    id:              "tph-bunkyo-hakusan-residence",
    name:            "ザ・パークハウス 文京白山レジデンス",
    developers:      ["三菱地所レジデンス"],
    ward:            "文京区",
    address:         "文京区白山",
    lat:             35.7181,
    lng:             139.7512,
    status:          "建築予定",
    floors:          null,
    total_units:     70,
    site_area:       null,
    area_min:        45.2,
    area_max:        98.45,
    completion:      null,
    delivery:        null,
    constructor:     null,
    parking:         null,
    bicycle_parking: null,
    ceiling_height:  null,
    floor_method:    null,
    disposer:        null,
    eco_type:        null,
    corridor:        null,
    url:             "https://www.mecsumai.com/tph-bunkyohakusan/",
    updated_at:      "2026-04-18",
  },
  {
    id:              "tph-kita-akabanedai-tower",
    name:            "ザ・パークハウス 赤羽台タワー＆レジデンス",
    developers:      ["三菱地所レジデンス", "住友商事", "近鉄不動産"],
    ward:            "北区",
    address:         "北区赤羽台",
    lat:             35.780883,
    lng:             139.7173606,
    status:          "建築予定",
    floors:          null,
    total_units:     550,
    site_area:       null,
    area_min:        31.33,
    area_max:        138.41,
    completion:      null,
    delivery:        null,
    constructor:     null,
    parking:         null,
    bicycle_parking: null,
    ceiling_height:  null,
    floor_method:    null,
    disposer:        null,
    eco_type:        "ZEH-M",
    corridor:        null,
    url:             "https://www.mecsumai.com/tph-akabanedai/",
    updated_at:      "2026-04-18",
  },
  {
    id:              "tph-koto-kameido9",
    name:            "ザ・パークハウス 亀戸九丁目",
    developers:      ["三菱地所レジデンス"],
    ward:            "江東区",
    address:         "江東区亀戸9丁目",
    lat:             35.6923413,
    lng:             139.8294781,
    status:          "建築予定",
    floors:          13,
    total_units:     99,
    site_area:       null,
    area_min:        29.1,
    area_max:        73.08,
    completion:      "2026年7月下旬",
    delivery:        "2026年7月下旬",
    constructor:     null,
    parking:         null,
    bicycle_parking: null,
    ceiling_height:  null,
    floor_method:    null,
    disposer:        null,
    eco_type:        null,
    corridor:        null,
    url:             "https://www.mecsumai.com/tph-kameido9/",
    updated_at:      "2026-04-18",
  },
  {
    id:              "tph-nakano-higashinakano-place",
    name:            "ザ・パークハウス 東中野プレイス",
    developers:      ["三菱地所レジデンス"],
    ward:            "中野区",
    address:         "中野区東中野",
    lat:             35.7123261,
    lng:             139.6850551,
    status:          "建築予定",
    floors:          19,
    total_units:     72,
    site_area:       null,
    area_min:        56.63,
    area_max:        68.38,
    completion:      null,
    delivery:        null,
    constructor:     null,
    parking:         null,
    bicycle_parking: null,
    ceiling_height:  null,
    floor_method:    null,
    disposer:        null,
    eco_type:        null,
    corridor:        null,
    url:             "https://www.mecsumai.com/tph-higashinakano-p/",
    updated_at:      "2026-04-18",
  },
  {
    id:              "tph-shinagawa-megurofudomae-residence",
    name:            "ザ・パークハウス 目黒不動前レジデンス",
    developers:      ["三菱地所レジデンス"],
    ward:            "品川区",
    address:         "品川区西五反田",
    lat:             35.6250951,
    lng:             139.721865,
    status:          "建築予定",
    floors:          null,
    total_units:     126,
    site_area:       null,
    area_min:        31.98,
    area_max:        70.95,
    completion:      "2028年4月中旬",
    delivery:        "2028年5月下旬",
    constructor:     null,
    parking:         null,
    bicycle_parking: null,
    ceiling_height:  null,
    floor_method:    null,
    disposer:        null,
    eco_type:        null,
    corridor:        null,
    url:             "https://www.mecsumai.com/tph-megurofudomae-r/",
    updated_at:      "2026-04-18",
  },
  {
    id:              "tph-setagaya-yoga-place",
    name:            "ザ・パークハウス 用賀プレイス",
    developers:      ["三菱地所レジデンス", "NTT都市開発"],
    ward:            "世田谷区",
    address:         "世田谷区玉川台",
    lat:             35.6234396,
    lng:             139.6279065,
    status:          "分譲中",
    floors:          12,
    total_units:     83,
    site_area:       null,
    area_min:        46.35,
    area_max:        85.97,
    completion:      null,
    delivery:        null,
    constructor:     null,
    parking:         null,
    bicycle_parking: null,
    ceiling_height:  null,
    floor_method:    null,
    disposer:        null,
    eco_type:        null,
    corridor:        null,
    url:             "https://www.mecsumai.com/tph-yoga-p/",
    updated_at:      "2026-04-18",
  },
  {
    id:              "tph-shinjuku-tomihisa",
    name:            "ザ・パークハウス 新宿富久町",
    developers:      ["三菱地所レジデンス"],
    ward:            "新宿区",
    address:         "新宿区富久町",
    lat:             35.6933276,
    lng:             139.7156486,
    status:          "建築予定",
    floors:          null,
    total_units:     50,
    site_area:       null,
    area_min:        51.93,
    area_max:        70.83,
    completion:      null,
    delivery:        null,
    constructor:     null,
    parking:         null,
    bicycle_parking: null,
    ceiling_height:  null,
    floor_method:    null,
    disposer:        null,
    eco_type:        "ZEH-M Oriented",
    corridor:        null,
    url:             "https://www.mecsumai.com/tph-shinjuku-tomihisa/",
    updated_at:      "2026-04-18",
  },
  {
    id:              "tph-chiyoda-3bancho",
    name:            "ザ・パークハウス 千代田三番町",
    developers:      ["三菱地所レジデンス"],
    ward:            "千代田区",
    address:         "千代田区三番町",
    lat:             35.6903981,
    lng:             139.7408723,
    status:          "建築予定",
    floors:          null,
    total_units:     58,
    site_area:       null,
    area_min:        70.7,
    area_max:        78.61,
    completion:      null,
    delivery:        null,
    constructor:     null,
    parking:         null,
    bicycle_parking: null,
    ceiling_height:  null,
    floor_method:    null,
    disposer:        null,
    eco_type:        null,
    corridor:        null,
    url:             "https://www.mecsumai.com/tph-c3bancho/",
    updated_at:      "2026-04-18",
  },
  {
    id:              "tph-koto-monnakacho",
    name:            "ザ・パークハウス 門前仲町",
    developers:      ["三菱地所レジデンス", "三菱倉庫"],
    ward:            "江東区",
    address:         "江東区佐賀",
    lat:             35.6791,
    lng:             139.7946,
    status:          "分譲中",
    floors:          null,
    total_units:     240,
    site_area:       5600,
    area_min:        59.62,
    area_max:        72.78,
    completion:      null,
    delivery:        null,
    constructor:     null,
    parking:         null,
    bicycle_parking: null,
    ceiling_height:  null,
    floor_method:    null,
    disposer:        null,
    eco_type:        null,
    corridor:        null,
    url:             "https://www.mecsumai.com/tph-monnaka/",
    updated_at:      "2026-04-18",
  },
  {
    id:              "branz-bunkyo-gokokuji-fujimizaka",
    name:            "ブランズ護国寺富士見坂",
    developers:      ["東急不動産"],
    ward:            "文京区",
    address:         "文京区大塚二丁目110番3",
    lat:             35.7124,
    lng:             139.7332,
    status:          "分譲中",
    floors:          10,
    total_units:     36,
    site_area:       null,
    area_min:        70.02,
    area_max:        74.31,
    completion:      null,
    delivery:        null,
    constructor:     null,
    parking:         null,
    bicycle_parking: null,
    ceiling_height:  null,
    floor_method:    null,
    disposer:        null,
    eco_type:        null,
    corridor:        null,
    url:             "https://sumai.tokyu-land.co.jp/branz/gokokuji/",
    updated_at:      "2026-04-18",
  },
  {
    id:              "branz-minato-shibaura",
    name:            "ブランズ芝浦",
    developers:      ["東急不動産"],
    ward:            "港区",
    address:         "港区芝浦4丁目",
    lat:             35.6383662,
    lng:             139.746397,
    status:          "分譲中",
    floors:          null,
    total_units:     62,
    site_area:       null,
    area_min:        43.65,
    area_max:        93.37,
    completion:      null,
    delivery:        null,
    constructor:     null,
    parking:         null,
    bicycle_parking: null,
    ceiling_height:  null,
    floor_method:    null,
    disposer:        null,
    eco_type:        null,
    corridor:        null,
    url:             "https://sumai.tokyu-land.co.jp/branz/shibaura4/",
    updated_at:      "2026-04-18",
  },
  {
    id:              "branz-city-shinagawa-renaicanal",
    name:            "ブランズシティ品川ルネ キャナル",
    developers:      ["東急不動産"],
    ward:            "港区",
    address:         "港区港南四丁目20番1他",
    lat:             35.6198,
    lng:             139.7417,
    status:          "分譲中",
    floors:          19,
    total_units:     233,
    site_area:       null,
    area_min:        56.33,
    area_max:        80.68,
    completion:      null,
    delivery:        null,
    constructor:     null,
    parking:         null,
    bicycle_parking: null,
    ceiling_height:  null,
    floor_method:    null,
    disposer:        null,
    eco_type:        null,
    corridor:        null,
    url:             "https://sumai.tokyu-land.co.jp/branz/shinagawa-renaicanal/",
    updated_at:      "2026-04-18",
  },
  {
    id:              "branz-city-shinagawa-terrace",
    name:            "ブランズシティ品川テラス",
    developers:      ["東急不動産"],
    ward:            "港区",
    address:         "港区港南四丁目29番5",
    lat:             35.6195,
    lng:             139.7430,
    status:          "分譲中",
    floors:          null,
    total_units:     216,
    site_area:       null,
    area_min:        61.67,
    area_max:        80.57,
    completion:      null,
    delivery:        null,
    constructor:     null,
    parking:         null,
    bicycle_parking: null,
    ceiling_height:  null,
    floor_method:    null,
    disposer:        null,
    eco_type:        null,
    corridor:        null,
    url:             "https://sumai.tokyu-land.co.jp/branz/shinagawa-terrace/",
    updated_at:      "2026-04-18",
  },
  {
    id:              "branz-minato-shirokanedai5",
    name:            "ブランズ白金台五丁目",
    developers:      ["東急不動産"],
    ward:            "港区",
    address:         "港区白金台五丁目253番5",
    lat:             35.6379,
    lng:             139.7221,
    status:          "分譲中",
    floors:          null,
    total_units:     32,
    site_area:       null,
    area_min:        68.38,
    area_max:        68.38,
    completion:      null,
    delivery:        null,
    constructor:     null,
    parking:         null,
    bicycle_parking: null,
    ceiling_height:  null,
    floor_method:    null,
    disposer:        null,
    eco_type:        null,
    corridor:        null,
    url:             "https://sumai.tokyu-land.co.jp/branz/shirokanedai5/",
    updated_at:      "2026-04-18",
  },
  {
    id:              "lions-bunkyo-hongo",
    name:            "ザ・ライオンズ本郷",
    developers:      ["大京"],
    ward:            "文京区",
    address:         "文京区本郷",
    lat:             35.7025699,
    lng:             139.7564014,
    status:          "分譲中",
    floors:          null,
    total_units:     null,
    site_area:       null,
    area_min:        45,
    area_max:        115,
    completion:      null,
    delivery:        null,
    constructor:     null,
    parking:         null,
    bicycle_parking: null,
    ceiling_height:  null,
    floor_method:    null,
    disposer:        null,
    eco_type:        null,
    corridor:        null,
    url:             "https://lions-mansion.jp/MN220016/",
    updated_at:      "2026-04-18",
  },
  {
    id:              "lions-setagaya-hachimanyama",
    name:            "ザ・ライオンズ世田谷八幡山",
    developers:      ["大京", "穴吹工務店"],
    ward:            "世田谷区",
    address:         "世田谷区八幡山",
    lat:             35.6650223,
    lng:             139.6138857,
    status:          "分譲中",
    floors:          null,
    total_units:     null,
    site_area:       null,
    area_min:        70.52,
    area_max:        84.31,
    completion:      null,
    delivery:        null,
    constructor:     null,
    parking:         null,
    bicycle_parking: null,
    ceiling_height:  null,
    floor_method:    null,
    disposer:        null,
    eco_type:        "ZEH-M",
    corridor:        null,
    url:             "https://lions-mansion.jp/MN220040/",
    updated_at:      "2026-04-18",
  },
  {
    id:              "lions-ota-okayama",
    name:            "ザ・ライオンズ大岡山",
    developers:      ["大京"],
    ward:            "大田区",
    address:         "大田区大岡山",
    lat:             35.6054,
    lng:             139.6837,
    status:          "分譲中",
    floors:          null,
    total_units:     35,
    site_area:       null,
    area_min:        81.3,
    area_max:        81.3,
    completion:      null,
    delivery:        null,
    constructor:     null,
    parking:         null,
    bicycle_parking: null,
    ceiling_height:  null,
    floor_method:    null,
    disposer:        null,
    eco_type:        null,
    corridor:        null,
    url:             "https://lions-mansion.jp/MN210098/",
    updated_at:      "2026-04-18",
  },
  {
    id:              "baus-suginami-kugayama",
    name:            "バウス久我山",
    developers:      ["中央日本土地建物", "長谷工コーポレーション"],
    ward:            "杉並区",
    address:         "杉並区久我山",
    lat:             35.681677,
    lng:             139.596308,
    status:          "分譲中",
    floors:          null,
    total_units:     139,
    site_area:       9000,
    area_min:        55,
    area_max:        106,
    completion:      null,
    delivery:        null,
    constructor:     null,
    parking:         null,
    bicycle_parking: null,
    ceiling_height:  null,
    floor_method:    null,
    disposer:        null,
    eco_type:        "ゼッチ",
    corridor:        null,
    url:             "https://www.baus-web.jp/baus/kugayama/",
    updated_at:      "2026-04-18",
  },
  {
    id:              "baus-adachi-kitaayase-tower",
    name:            "バウス北綾瀬タワー",
    developers:      ["中央日本土地建物", "長谷工コーポレーション"],
    ward:            "足立区",
    address:         "足立区北綾瀬",
    lat:             35.7633078,
    lng:             139.8319731,
    status:          "分譲中",
    floors:          20,
    total_units:     147,
    site_area:       null,
    area_min:        null,
    area_max:        null,
    completion:      null,
    delivery:        null,
    constructor:     null,
    parking:         null,
    bicycle_parking: null,
    ceiling_height:  null,
    floor_method:    null,
    disposer:        null,
    eco_type:        null,
    corridor:        null,
    url:             "https://www.baus-web.jp/baus/kitaayase/",
    updated_at:      "2026-04-18",
  },
  {
    id:              "openhouse-chiyoda-rokubancho",
    name:            "イノベイシア六番町",
    developers:      ["オープンハウス・ディベロップメント"],
    ward:            "千代田区",
    address:         "千代田区六番町5番18他",
    lat:             35.6917,
    lng:             139.7387,
    status:          "分譲中",
    floors:          null,
    total_units:     16,
    site_area:       null,
    area_min:        60.1,
    area_max:        119.31,
    completion:      "2026年4月下旬",
    delivery:        null,
    constructor:     null,
    parking:         null,
    bicycle_parking: null,
    ceiling_height:  null,
    floor_method:    null,
    disposer:        null,
    eco_type:        null,
    corridor:        null,
    url:             "https://ms.ohd.openhouse-group.com/bukken/kanto/rokubancho/",
    updated_at:      "2026-04-18",
  },
  {
    id:              "openhouse-meguro-inovasia-ebisu",
    name:            "イノベイシア恵比寿",
    developers:      ["オープンハウス・ディベロップメント"],
    ward:            "目黒区",
    address:         "目黒区三田二丁目144番3",
    lat:             35.6387,
    lng:             139.7183,
    status:          "分譲中",
    floors:          null,
    total_units:     46,
    site_area:       null,
    area_min:        71.54,
    area_max:        82.85,
    completion:      null,
    delivery:        null,
    constructor:     null,
    parking:         null,
    bicycle_parking: null,
    ceiling_height:  null,
    floor_method:    null,
    disposer:        null,
    eco_type:        null,
    corridor:        null,
    url:             "https://ms.ohd.openhouse-group.com/bukken/kanto/ivcebisu/",
    updated_at:      "2026-04-18",
  },
  {
    id:              "openhouse-shibuya-inovas-yoyogi",
    name:            "イノバス代々木",
    developers:      ["オープンハウス・ディベロップメント"],
    ward:            "渋谷区",
    address:         "渋谷区代々木三丁目31番1",
    lat:             35.6800,
    lng:             139.6967,
    status:          "建築予定",
    floors:          null,
    total_units:     20,
    site_area:       null,
    area_min:        65.49,
    area_max:        92.66,
    completion:      null,
    delivery:        null,
    constructor:     null,
    parking:         null,
    bicycle_parking: null,
    ceiling_height:  null,
    floor_method:    null,
    disposer:        null,
    eco_type:        null,
    corridor:        null,
    url:             "https://ms.ohd.openhouse-group.com/bukken/kanto/ivyoyogi/",
    updated_at:      "2026-04-18",
  },
  {
    id:              "openhouse-shinjuku-inovas-nakanomachi",
    name:            "イノバス市谷仲之町",
    developers:      ["オープンハウス・ディベロップメント"],
    ward:            "新宿区",
    address:         "新宿区市谷仲之町1番5",
    lat:             35.6903,
    lng:             139.7291,
    status:          "建築予定",
    floors:          null,
    total_units:     21,
    site_area:       null,
    area_min:        36,
    area_max:        79,
    completion:      null,
    delivery:        null,
    constructor:     null,
    parking:         null,
    bicycle_parking: null,
    ceiling_height:  null,
    floor_method:    null,
    disposer:        null,
    eco_type:        null,
    corridor:        "内廊下",
    url:             "https://ms.ohd.openhouse-group.com/bukken/kanto/nakanocho/",
    updated_at:      "2026-04-18",
  },
  {
    id:              "openhouse-toshima-inovas-mejiro",
    name:            "イノバス目白",
    developers:      ["オープンハウス・ディベロップメント"],
    ward:            "豊島区",
    address:         "豊島区目白三丁目",
    lat:             35.722128,
    lng:             139.7060491,
    status:          "建築予定",
    floors:          null,
    total_units:     24,
    site_area:       null,
    area_min:        61.58,
    area_max:        70.26,
    completion:      null,
    delivery:        null,
    constructor:     null,
    parking:         null,
    bicycle_parking: null,
    ceiling_height:  null,
    floor_method:    null,
    disposer:        null,
    eco_type:        null,
    corridor:        "内廊下",
    url:             "https://ms.ohd.openhouse-group.com/bukken/kanto/ivmejiro/",
    updated_at:      "2026-04-18",
  },
  {
    id:              "openhouse-kita-inovas-ojihoncho",
    name:            "イノバス王子本町",
    developers:      ["オープンハウス・ディベロップメント"],
    ward:            "北区",
    address:         "北区王子本町一丁目4番1",
    lat:             35.7539,
    lng:             139.7413,
    status:          "建築予定",
    floors:          null,
    total_units:     36,
    site_area:       null,
    area_min:        47.32,
    area_max:        99.06,
    completion:      null,
    delivery:        null,
    constructor:     null,
    parking:         null,
    bicycle_parking: null,
    ceiling_height:  null,
    floor_method:    null,
    disposer:        null,
    eco_type:        null,
    corridor:        null,
    url:             "https://ms.ohd.openhouse-group.com/bukken/kanto/ivojihoncho/",
    updated_at:      "2026-04-18",
  },
  {
    id:              "openhouse-taito-okachimachi",
    name:            "オープンレジデンシア御徒町",
    developers:      ["オープンハウス・ディベロップメント"],
    ward:            "台東区",
    address:         "台東区台東2丁目102番1他",
    lat:             35.7085,
    lng:             139.7769,
    status:          "分譲中",
    floors:          null,
    total_units:     30,
    site_area:       null,
    area_min:        55.51,
    area_max:        55.51,
    completion:      null,
    delivery:        null,
    constructor:     null,
    parking:         null,
    bicycle_parking: null,
    ceiling_height:  null,
    floor_method:    null,
    disposer:        null,
    eco_type:        null,
    corridor:        null,
    url:             "https://ms.ohd.openhouse-group.com/bukken/kanto/okachimachi/",
    updated_at:      "2026-04-18",
  },
  {
    id:              "openhouse-shinagawa-inovas-fudomae",
    name:            "イノバス不動前",
    developers:      ["オープンハウス・ディベロップメント"],
    ward:            "品川区",
    address:         "品川区西五反田四丁目646番1他",
    lat:             35.6326,
    lng:             139.7130,
    status:          "建築予定",
    floors:          null,
    total_units:     154,
    site_area:       null,
    area_min:        36.85,
    area_max:        64.13,
    completion:      null,
    delivery:        null,
    constructor:     null,
    parking:         null,
    bicycle_parking: null,
    ceiling_height:  null,
    floor_method:    null,
    disposer:        null,
    eco_type:        null,
    corridor:        null,
    url:             "https://ms.ohd.openhouse-group.com/bukken/kanto/fudomae/",
    updated_at:      "2026-04-18",
  },
  {
    id:              "ober-adachi-rokucho-residence",
    name:            "オーベル六町レジデンス",
    developers:      ["大成有楽不動産"],
    ward:            "足立区",
    address:         "足立区六町1丁目13番19他",
    lat:             35.7705,
    lng:             139.8481,
    status:          "建築予定",
    floors:          9,
    total_units:     78,
    site_area:       1517,
    area_min:        33.58,
    area_max:        66.12,
    completion:      "2027年10月",
    delivery:        "2027年12月",
    constructor:     "新日本建設",
    parking:         "14台（平置13・身障者1）",
    bicycle_parking: 137,
    ceiling_height:  null,
    floor_method:    null,
    disposer:        null,
    eco_type:        null,
    corridor:        null,
    url:             "https://www.ober.jp/rokucho/",
    updated_at:      "2026-04-18",
  },
  {
    id:              "ober-itabashi-tobunerima",
    name:            "オーベルアーバンツ東武練馬",
    developers:      ["大成有楽不動産"],
    ward:            "板橋区",
    address:         "板橋区徳丸三丁目117番2",
    lat:             35.7695,
    lng:             139.6569,
    status:          "建築中",
    floors:          5,
    total_units:     33,
    site_area:       948.03,
    area_min:        42.3,
    area_max:        95.97,
    completion:      "2027年8月下旬",
    delivery:        "2027年10月下旬",
    constructor:     "鍜治田工務店",
    parking:         "1台（身障者用）",
    bicycle_parking: 32,
    ceiling_height:  null,
    floor_method:    null,
    disposer:        null,
    eco_type:        null,
    corridor:        null,
    url:             "https://www.ober.jp/tobu-nerima/",
    updated_at:      "2026-04-18",
  },
  {
    id:              "ober-taito-akihabara",
    name:            "オーベルアーバンツ秋葉原",
    developers:      ["大成有楽不動産"],
    ward:            "台東区",
    address:         "台東区浅草橋4丁目2番1他",
    lat:             35.6975,
    lng:             139.7833,
    status:          "分譲中",
    floors:          14,
    total_units:     85,
    site_area:       784.91,
    area_min:        35.33,
    area_max:        65.52,
    completion:      "2026年4月中旬",
    delivery:        "2026年5月下旬",
    constructor:     "東鉄工業",
    parking:         "17台（平置2・機械式15）",
    bicycle_parking: 131,
    ceiling_height:  null,
    floor_method:    null,
    disposer:        null,
    eco_type:        "ZEH-M Oriented",
    corridor:        "内廊下",
    url:             "https://www.ober.jp/urvanz-akihabara/",
    updated_at:      "2026-04-18",
  },
  {
    id:              "crevia-arakawa-machiya-residence",
    name:            "クレヴィア町屋レジデンス",
    developers:      ["伊藤忠都市開発"],
    ward:            "荒川区",
    address:         "荒川区荒川四丁目4番4他",
    lat:             35.7322,
    lng:             139.7938,
    status:          "分譲中",
    floors:          null,
    total_units:     53,
    site_area:       null,
    area_min:        55,
    area_max:        109,
    completion:      null,
    delivery:        "2027年10月下旬",
    constructor:     null,
    parking:         null,
    bicycle_parking: null,
    ceiling_height:  null,
    floor_method:    null,
    disposer:        null,
    eco_type:        null,
    corridor:        null,
    url:             "https://www.itochu-sumai.com/machiya-r53/",
    updated_at:      "2026-04-18",
  },
  {
    id:              "crevia-suginami-hamadayama",
    name:            "クレヴィア浜田山",
    developers:      ["伊藤忠都市開発"],
    ward:            "杉並区",
    address:         "杉並区浜田山三丁目966番2",
    lat:             35.6779,
    lng:             139.6352,
    status:          "分譲中",
    floors:          null,
    total_units:     34,
    site_area:       null,
    area_min:        44.64,
    area_max:        107.76,
    completion:      null,
    delivery:        null,
    constructor:     null,
    parking:         null,
    bicycle_parking: null,
    ceiling_height:  null,
    floor_method:    null,
    disposer:        null,
    eco_type:        null,
    corridor:        "内廊下",
    url:             "https://www.itochu-sumai.com/hamadayama/",
    updated_at:      "2026-04-18",
  },
  {
    id:              "crevia-setagaya-kinuta-thecourt",
    name:            "クレヴィア世田谷砧ザ・コート",
    developers:      ["伊藤忠都市開発"],
    ward:            "世田谷区",
    address:         "世田谷区砧四丁目259番1",
    lat:             35.6365,
    lng:             139.6167,
    status:          "分譲中",
    floors:          null,
    total_units:     31,
    site_area:       null,
    area_min:        45,
    area_max:        89,
    completion:      null,
    delivery:        "2027年1月下旬",
    constructor:     null,
    parking:         null,
    bicycle_parking: null,
    ceiling_height:  null,
    floor_method:    null,
    disposer:        null,
    eco_type:        "ゼッチ",
    corridor:        null,
    url:             "https://www.itochu-sumai.com/setagaya-kinuta/",
    updated_at:      "2026-04-18",
  },
]
