import type { PolicyLayer } from '@/lib/supabase/types'

export interface SeedPolicy {
  id: string
  layer: PolicyLayer
  prefecture: string | null  // 都道府県名（pref/ward/tokyoレイヤーに使用）
  ward: string | null
  name: string
  category: string | null
  summary: string
  description: string | null
  amount_monthly: number | null
  amount_lump: number | null
  amount_note: string | null
  apply_method: string | null
  apply_url: string | null
  status: 'approved'
  policy_conditions: Array<{
    child_age_min_months: number | null
    child_age_max_months: number | null
    birth_order_min: number | null
    birth_order_max: number | null
    income_min_man_yen: number | null
    income_max_man_yen: number | null
  }>
}

export const SEED_POLICIES: SeedPolicy[] = [
  {
    id: "seed-001",
    layer: "national",
    prefecture: null,
    ward: null,
    name: "児童手当",
    category: null,
    summary: "0歳から高校生まで毎月支給される国の給付金（所得制限なし）",
    description: "2024年10月から所得制限が完全撤廃され、高校生（18歳年度末）まで対象が拡充。第3子以降は月額30,000円に増額。",
    amount_monthly: 10000,
    amount_lump: null,
    amount_note: "0〜2歳:月15,000円 / 3歳〜高校生:月10,000円 / 第3子以降:月30,000円",
    apply_method: "出生後（または転入後）15日以内に居住区の区役所へ申請。マイナポータルからオンライン申請も可。",
    apply_url: "https://www.cfa.go.jp/policies/kokoseido/jidouteate/",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: 0,
      child_age_max_months: 215,
      birth_order_min: null,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: null,
    }],
  },
  {
    id: "seed-002",
    layer: "national",
    prefecture: null,
    ward: null,
    name: "出産育児一時金",
    category: null,
    summary: "健康保険から出産時に一括50万円が支給される",
    description: "健康保険（または国民健康保険）加入者が対象。出産1件につき50万円が支給。直接支払制度を使うと病院に直接支払われるため窓口負担なし。産科医療補償制度未加入施設では488,000円。",
    amount_monthly: null,
    amount_lump: 500000,
    amount_note: "産科医療補償制度未加入施設での出産は488,000円",
    apply_method: "直接支払制度（病院への直接支払）を利用するか、出産後に健康保険組合または区役所国保窓口へ申請",
    apply_url: "https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/kenkou_iryou/iryouhoken/shussan/index.html",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: 0,
      child_age_max_months: 3,
      birth_order_min: null,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: null,
    }],
  },
  {
    id: "seed-003",
    layer: "tokyo",
    prefecture: "東京都",
    ward: null,
    name: "018サポート（東京都）",
    category: null,
    summary: "0〜18歳の子ども1人あたり月5,000円（年6万円）を支給。所得制限なし",
    description: "東京都独自の給付金。0歳から18歳（18歳の誕生日が属する年度末まで）の子ども全員が対象。所得制限なし。4ヶ月ごとに15,000円（月5,000円相当）が振り込まれる。",
    amount_monthly: 5000,
    amount_lump: null,
    amount_note: "年間60,000円（4ヶ月ごとに15,000円振込）",
    apply_method: "東京都の専用サイト（018support.metro.tokyo.lg.jp）からオンライン申請",
    apply_url: "https://018support.metro.tokyo.lg.jp/",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: 0,
      child_age_max_months: 215,
      birth_order_min: null,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: null,
    }],
  },
  {
    id: "seed-004",
    layer: "tokyo",
    prefecture: "東京都",
    ward: null,
    name: "東京都 赤ちゃんファースト",
    category: null,
    summary: "出産家庭に10万円相当のギフトカタログを贈呈",
    description: "都内在住で2023年4月1日以降に生まれた子どもがいる家庭が対象。育児用品・食料品・サービス等から選べる10万円相当のカタログギフト。",
    amount_monthly: null,
    amount_lump: 100000,
    amount_note: "10万円相当のカタログギフト（商品・サービスから選択）",
    apply_method: "区市町村の窓口または専用サイトから申請（出生後申請）",
    apply_url: "https://www.fukushi.metro.tokyo.lg.jp/kodomo/index.html",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: 0,
      child_age_max_months: 12,
      birth_order_min: null,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: null,
    }],
  },
  {
    id: "seed-005",
    layer: "ward",
    prefecture: "東京都",
    ward: "港区",
    name: "港区 子ども医療費助成",
    category: null,
    summary: "中学校卒業まで医療費が無料（所得制限なし）",
    description: "港区では0歳から中学校卒業（15歳到達後の3月31日）まで、保険診療内の医療費（入院・通院）が実質無料。住民税非課税世帯は高校生まで対象。",
    amount_monthly: null,
    amount_lump: null,
    amount_note: "保険診療内の医療費（入院・通院）が実質0円",
    apply_method: "出生届提出時または転入時に港区役所へ申請（医療証が発行される）",
    apply_url: "https://www.city.minato.tokyo.jp/jidouiryou/index.html",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: 0,
      child_age_max_months: 179,
      birth_order_min: null,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: null,
    }],
  },
  {
    id: "seed-006",
    layer: "ward",
    prefecture: "東京都",
    ward: "港区",
    name: "港区 子育て支援商品券（バースデーサポート）",
    category: null,
    summary: "就学前の子ども1人あたり毎年誕生月に3万円分の商品券を贈呈",
    description: "港区在住の就学前（0〜5歳）の子どもに、誕生月に区内で使える商品券3万円分を贈呈。毎年もらえるため、5年間で最大15万円分。",
    amount_monthly: null,
    amount_lump: 30000,
    amount_note: "就学前まで毎年誕生月に3万円分の商品券（5年間で最大15万円）",
    apply_method: "港区役所窓口または郵送にて申請",
    apply_url: "https://www.city.minato.tokyo.jp/kosodate/index.html",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: 0,
      child_age_max_months: 71,
      birth_order_min: null,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: null,
    }],
  },
  {
    id: "seed-007",
    layer: "ward",
    prefecture: "東京都",
    ward: "品川区",
    name: "品川区 子ども医療費助成",
    category: null,
    summary: "高校生まで医療費が無料（所得制限なし）",
    description: "品川区では0歳から高校卒業（18歳到達後の3月31日）まで医療費（保険診療内）が無料。東京都の助成に品川区が独自に上乗せし、高校生まで拡大。",
    amount_monthly: null,
    amount_lump: null,
    amount_note: "高校生まで保険診療内の医療費が0円",
    apply_method: "転入時または出生届提出時に品川区役所へ申請",
    apply_url: "https://www.city.shinagawa.tokyo.jp/PC/kosodate/index.html",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: 0,
      child_age_max_months: 215,
      birth_order_min: null,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: null,
    }],
  },
  {
    id: "seed-008",
    layer: "ward",
    prefecture: "東京都",
    ward: "品川区",
    name: "品川区 出産祝金",
    category: null,
    summary: "区内在住の子どもが生まれた家庭に出産祝金を支給",
    description: "品川区在住で出産した家庭に一時金を支給。第1子:1万円、第2子:2万円、第3子以降:10万円。",
    amount_monthly: null,
    amount_lump: 10000,
    amount_note: "第1子:10,000円 / 第2子:20,000円 / 第3子以降:100,000円",
    apply_method: "出生届提出後、品川区役所窓口にて申請",
    apply_url: "https://www.city.shinagawa.tokyo.jp/PC/kosodate/index.html",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: 0,
      child_age_max_months: 6,
      birth_order_min: null,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: null,
    }],
  },
  {
    id: "seed-009",
    layer: "ward",
    prefecture: "東京都",
    ward: "目黒区",
    name: "目黒区 子ども医療費助成",
    category: null,
    summary: "高校生まで医療費が無料（所得制限なし）",
    description: "目黒区では0歳から高校卒業（18歳到達後の3月31日）まで医療費（保険診療内の入院・通院）が無料。",
    amount_monthly: null,
    amount_lump: null,
    amount_note: "高校生まで保険診療内の医療費が0円",
    apply_method: "出生届提出時または転入時に目黒区役所へ申請",
    apply_url: "https://www.city.meguro.tokyo.jp/kosodate/index.html",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: 0,
      child_age_max_months: 215,
      birth_order_min: null,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: null,
    }],
  },
  {
    id: "seed-010",
    layer: "ward",
    prefecture: "東京都",
    ward: "目黒区",
    name: "目黒区 出産・子育て応援交付金",
    category: null,
    summary: "妊娠届・出生届時に計10万円分のクーポンを支給",
    description: "国の「出産・子育て応援交付金」を目黒区が実施。妊娠届時に5万円分（伴走型相談支援）、出生後に5万円分（計10万円）のギフトカタログまたはクーポンを支給。",
    amount_monthly: null,
    amount_lump: 100000,
    amount_note: "妊娠届時5万円 ＋ 出生時5万円（合計10万円）",
    apply_method: "妊娠届提出時に区役所で案内。出生後は別途申請が必要。",
    apply_url: "https://www.city.meguro.tokyo.jp/kosodate/index.html",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: 0,
      child_age_max_months: 6,
      birth_order_min: null,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: null,
    }],
  },
  {
    id: "seed-011",
    layer: "ward",
    prefecture: "東京都",
    ward: "江東区",
    name: "江東区 子ども医療費助成",
    category: null,
    summary: "高校生まで医療費が無料（所得制限なし）",
    description: "江東区では0歳から高校卒業（18歳到達後の3月31日）まで医療費（保険診療内の入院・通院）が無料。",
    amount_monthly: null,
    amount_lump: null,
    amount_note: "高校生まで保険診療内の医療費が0円",
    apply_method: "出生届提出時または転入時に江東区役所へ申請",
    apply_url: "https://www.city.koto.lg.jp/390101/kosodate/index.html",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: 0,
      child_age_max_months: 215,
      birth_order_min: null,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: null,
    }],
  },
  {
    id: "seed-012",
    layer: "ward",
    prefecture: "東京都",
    ward: "江東区",
    name: "江東区 誕生祝品",
    category: null,
    summary: "区内出生の子どもに誕生祝品（商品券等）を贈呈",
    description: "江東区在住で出生した子どもに誕生祝品として商品券等を贈呈。第3子以降は増額される。",
    amount_monthly: null,
    amount_lump: 10000,
    amount_note: "第3子以降は増額あり",
    apply_method: "区役所窓口にて出生届と同時に申請",
    apply_url: "https://www.city.koto.lg.jp/390101/kosodate/index.html",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: 0,
      child_age_max_months: 3,
      birth_order_min: null,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: null,
    }],
  },
  {
    id: "seed-013",
    layer: "ward",
    prefecture: "東京都",
    ward: "江戸川区",
    name: "江戸川区 子ども医療費助成",
    category: null,
    summary: "高校生まで医療費が無料（所得制限なし）",
    description: "江戸川区では0歳から高校卒業（18歳到達後の3月31日）まで医療費（保険診療内の入院・通院）が無料。",
    amount_monthly: null,
    amount_lump: null,
    amount_note: "高校生まで保険診療内の医療費が0円",
    apply_method: "出生届提出時または転入時に江戸川区役所へ申請",
    apply_url: "https://www.city.edogawa.tokyo.jp/kosodate/index.html",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: 0,
      child_age_max_months: 215,
      birth_order_min: null,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: null,
    }],
  },
  {
    id: "seed-014",
    layer: "ward",
    prefecture: "東京都",
    ward: "江戸川区",
    name: "江戸川区 こんにちは赤ちゃん事業（育児支援）",
    category: null,
    summary: "生後4ヶ月以内の全家庭に保健師が訪問し育児グッズを贈呈",
    description: "江戸川区では生後4ヶ月以内の赤ちゃんがいる全家庭を保健師・助産師が訪問。育児相談に加え、おむつ等の育児支援グッズを現物で提供。申請不要。",
    amount_monthly: null,
    amount_lump: null,
    amount_note: "育児支援グッズ（おむつ等）の現物支給",
    apply_method: "申請不要（区が自動的に訪問）",
    apply_url: "https://www.city.edogawa.tokyo.jp/kosodate/index.html",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: 0,
      child_age_max_months: 4,
      birth_order_min: null,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: null,
    }],
  },
  {
    id: "seed-015",
    layer: "national",
    prefecture: null,
    ward: null,
    name: "幼児教育・保育の無償化（3〜5歳）",
    category: "保育・教育",
    summary: "3〜5歳全員の認可保育所・幼稚園等の保育料が無料",
    description: "子ども・子育て支援法に基づき、3歳〜5歳（年少〜年長）の全ての子どもを対象に、認可保育所・幼稚園・認定こども園等の保育料が無料。認可外保育施設（企業主導型保育・地方裁量型等）も月37,000円まで補助。2019年10月開始。所得制限なし。",
    amount_monthly: null,
    amount_lump: null,
    amount_note: "認可保育所・幼稚園等の保育料が月0円（認可外保育施設は月3.7万円まで補助）",
    apply_method: "保育所・幼稚園等の入所手続き時に自動適用（別途申請は原則不要、施設に確認を）",
    apply_url: "https://www.cfa.go.jp/policies/kokoseido/mushouka/",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: 36,
      child_age_max_months: 71,
      birth_order_min: null,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: null,
    }],
  },
  {
    id: "seed-016",
    layer: "national",
    prefecture: null,
    ward: null,
    name: "幼児教育・保育の無償化（0〜2歳・低所得世帯）",
    category: "保育・教育",
    summary: "住民税非課税世帯（年収200万円以下目安）の0〜2歳は認可保育所の保育料が無料",
    description: "0〜2歳の子どもがいる住民税非課税世帯では、認可保育所等の保育料が無料。認可外保育施設も月42,000円（0歳）または月37,000円（1〜2歳）まで補助。国の幼児教育・保育の無償化の一環として2019年から実施。",
    amount_monthly: null,
    amount_lump: null,
    amount_note: "住民税非課税世帯は認可保育所の保育料が無料（認可外は月3.7〜4.2万円まで補助）",
    apply_method: "保育所入所申請時に自動判定（住民税非課税証明書が必要な場合あり）",
    apply_url: "https://www.cfa.go.jp/policies/kokoseido/mushouka/",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: 0,
      child_age_max_months: 35,
      birth_order_min: null,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: 200,
    }],
  },
  {
    id: "seed-017",
    layer: "national",
    prefecture: null,
    ward: null,
    name: "育児休業給付金（雇用保険）",
    category: "雇用・休業",
    summary: "育児休業中に休業前賃金の最大67%が最長2年間支給される",
    description: "雇用保険に加入している労働者が育児休業を取得した場合、育休開始から180日間は休業前賃金の67%、181日目以降は50%が最長2年間（子が2歳になるまで）支給される。両親ともに育休を取得した場合は「パパ・ママ育休プラス」により最長1年2ヶ月まで延長可。2025年度から給付率が最大80%に引き上げ予定。",
    amount_monthly: null,
    amount_lump: null,
    amount_note: "賃金の67%（6ヶ月経過後は50%）を最長23ヶ月支給。例：月収30万円の場合→月約20万円",
    apply_method: "ハローワークに申請（育休開始後、事業主を通じて2ヶ月ごとに申請）",
    apply_url: "https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/0000158500.html",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: 0,
      child_age_max_months: 23,
      birth_order_min: null,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: null,
    }],
  },
  {
    id: "seed-018",
    layer: "national",
    prefecture: null,
    ward: null,
    name: "出生時育児休業給付金（産後パパ育休）",
    category: "雇用・休業",
    summary: "産後8週以内に最大28日間の育休を取得すると賃金の67%が支給",
    description: "2022年10月施行の「産後パパ育休」制度。子どもの出生後8週間以内に最大28日間の育児休業を取得すると、雇用保険から休業前賃金の67%が支給される。2回に分割して取得することも可能。育休と社会保険料免除も適用される。",
    amount_monthly: null,
    amount_lump: null,
    amount_note: "最大28日間、賃金の67%を支給（例：月収30万円×67%÷30日×28日＝約18.8万円）",
    apply_method: "ハローワークへ申請（子の出生から8週間以内に育休開始・申請が必要）",
    apply_url: "https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/0000158500.html",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: 0,
      child_age_max_months: 2,
      birth_order_min: null,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: null,
    }],
  },
  {
    id: "seed-019",
    layer: "national",
    prefecture: null,
    ward: null,
    name: "高等学校等就学支援金（高校授業料無償化）",
    category: "保育・教育",
    summary: "年収910万円未満の世帯の高校授業料が国から支援される",
    description: "公立高校の授業料（年11.88万円相当）が支援される。年収590万円未満の世帯は私立高校の授業料もほぼ無償化（上限年39.6万円）。高専・専修学校等も対象。所得に応じた加算制度あり。",
    amount_monthly: null,
    amount_lump: null,
    amount_note: "公立高校：年間11.88万円分を支援 ／ 年収590万未満：私立高校も最大年39.6万円を支援",
    apply_method: "在籍する高校等を通じて申請（毎年度更新）",
    apply_url: "https://www.mext.go.jp/a_menu/shotou/mushouka/index.htm",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: 180,
      child_age_max_months: 215,
      birth_order_min: null,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: 910,
    }],
  },
  {
    id: "seed-020",
    layer: "national",
    prefecture: null,
    ward: null,
    name: "住宅ローン控除（子育て世帯・若者夫婦世帯特例）",
    category: "税制優遇",
    summary: "子育て世帯は住宅ローン控除の借入限度額が一般より大幅に優遇される",
    description: "2024〜2025年度入居の子育て世帯（18歳以下の子あり）・若者夫婦世帯は、住宅ローン控除の借入限度額が一般より引き上げられる。長期優良住宅等：5,000万円（一般は4,500万円）、ZEH住宅：4,500万円（一般は3,500万円）、省エネ住宅：4,000万円（一般は3,000万円）。控除率0.7%・控除期間13年間。合計所得2,000万円以下が対象。",
    amount_monthly: null,
    amount_lump: null,
    amount_note: "長期優良住宅等：借入限度額5,000万円 → 年最大35万円の税控除（13年間で最大455万円）",
    apply_method: "確定申告または年末調整（初年度のみ確定申告必須、入居翌年3月15日まで）",
    apply_url: "https://www.mlit.go.jp/jutakukentiku/house/jutakukentiku_house_tk2_000017.html",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: 0,
      child_age_max_months: 215,
      birth_order_min: null,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: 2000,
    }],
  },
  {
    id: "seed-021",
    layer: "tokyo",
    prefecture: "東京都",
    ward: null,
    name: "東京都 私立幼稚園等保護者補助金",
    category: "保育・教育",
    summary: "私立幼稚園等に通う3〜5歳の保育料を国の無償化に都が上乗せして補助",
    description: "東京都が私立幼稚園・認定こども園（幼稚園型）等に通う3〜5歳の子どもの保護者に補助金を支給。国の幼児教育無償化（月25,700円上限）に加えて、都が独自に上乗せ補助を実施。年収に応じて補助額が異なり、低所得世帯ほど補助が厚い。",
    amount_monthly: null,
    amount_lump: null,
    amount_note: "国の無償化（月最大25,700円）に加え、都が独自に上乗せ補助（所得に応じて変動）",
    apply_method: "在籍する幼稚園等を通じて申請（毎年度更新）",
    apply_url: "https://www.metro.tokyo.lg.jp/tosei/hodohappyo/press/2023/04/18/05.html",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: 36,
      child_age_max_months: 71,
      birth_order_min: null,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: null,
    }],
  },
  {
    id: "seed-022",
    layer: "tokyo",
    prefecture: "東京都",
    ward: null,
    name: "東京都 ベビーシッター利用支援事業",
    category: "育児サービス",
    summary: "ベビーシッターを1時間150円（最大1日9時間）で利用できる",
    description: "東京都が実施するベビーシッター利用支援。認可保育所等に入所できていない0〜2歳の子どもがいる家庭が対象。認定事業者のベビーシッターを通常料金の大幅割引で利用可能（利用者負担：1時間あたり150円）。育児や急な用事の際に活用できる。",
    amount_monthly: null,
    amount_lump: null,
    amount_note: "1時間150円（通常2,000〜3,000円を都が補助）、1日最大9時間・月160時間まで利用可",
    apply_method: "東京都の専用窓口または区市町村の窓口で申請（保育所未入所の証明が必要）",
    apply_url: "https://www.fukushi.metro.tokyo.lg.jp/kodomo/hoiku/babysitter.html",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: 0,
      child_age_max_months: 35,
      birth_order_min: null,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: null,
    }],
  },
  {
    id: "seed-023",
    layer: "tokyo",
    prefecture: "東京都",
    ward: null,
    name: "東京都 高校生等への授業料支援（都独自）",
    category: "保育・教育",
    summary: "国の就学支援金に上乗せし、都内私立高校の授業料を実質無償化",
    description: "東京都は2024年度から、国の就学支援金（最大年39.6万円）に加えて都独自の補助を実施し、都内私立高校等の授業料を実質無償化（上限年59.4万円）。2025年度からは所得制限を撤廃し、全所得世帯を対象に拡大予定。都内の私立高校は実質的に授業料無料となる。",
    amount_monthly: null,
    amount_lump: null,
    amount_note: "都内私立高校の授業料が実質無償（都が年間最大59.4万円を補助、所得制限撤廃予定）",
    apply_method: "在籍する高校等を通じて申請（毎年度更新）",
    apply_url: "https://www.metro.tokyo.lg.jp/tosei/hodohappyo/press/2024/01/30/17.html",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: 180,
      child_age_max_months: 215,
      birth_order_min: null,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: null,
    }],
  },
  {
    id: "seed-024",
    layer: "tokyo",
    prefecture: "東京都",
    ward: null,
    name: "東京都 産後ケア事業費補助",
    category: "育児サービス",
    summary: "産後ケア施設・助産院での宿泊・日帰りケアの利用料を大幅補助",
    description: "東京都が区市町村の産後ケア事業を補助することで、産後ケア施設・助産院でのデイサービス（日帰り）・ショートステイ（宿泊）型のケアを低負担で利用可能。都と区が費用の大半を補助し、利用者の自己負担を数百円〜数千円程度に軽減する。",
    amount_monthly: null,
    amount_lump: null,
    amount_note: "利用者自己負担：数百円〜数千円/回（通常1回5,000〜25,000円の大半を都・区が補助）",
    apply_method: "居住区の保健センター等に相談・申請（産後4ヶ月未満が多いが区により異なる）",
    apply_url: "https://www.fukushi.metro.tokyo.lg.jp/kodomo/madoguchi/sango.html",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: 0,
      child_age_max_months: 4,
      birth_order_min: null,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: null,
    }],
  },
  {
    id: "seed-025",
    layer: "ward",
    prefecture: "東京都",
    ward: "港区",
    name: "港区 認証保育所等利用補助金",
    category: "保育・教育",
    summary: "認証保育所等を利用する0〜2歳の子に月最大30,000円を補助",
    description: "港区では認証保育所・小規模保育所・家庭的保育事業を利用する0〜2歳の子どもの保護者に対し、利用料の一部を補助。認可保育所との保育料差額を軽減するための制度で、所得に応じて月最大30,000円の補助を受けられる。",
    amount_monthly: 30000,
    amount_lump: null,
    amount_note: "月最大30,000円を補助（所得により補助額が異なる場合あり）",
    apply_method: "港区役所子ども家庭支援センター等にて申請（保育施設入所と同時に手続き可）",
    apply_url: "https://www.city.minato.tokyo.jp/kosodate/index.html",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: 0,
      child_age_max_months: 35,
      birth_order_min: null,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: null,
    }],
  },
  {
    id: "seed-026",
    layer: "ward",
    prefecture: "東京都",
    ward: "港区",
    name: "港区 ベビーシッター利用支援",
    category: "育児サービス",
    summary: "都の支援（1時間150円）に加え、港区独自でベビーシッター利用料をさらに補助",
    description: "東京都のベビーシッター利用支援事業（1時間150円）に加えて、港区独自の補助を実施。認可保育所未入所の乳幼児を持つ家庭を中心に、ベビーシッター利用料の自己負担額を区がさらに軽減する。育児と仕事の両立を支援。",
    amount_monthly: null,
    amount_lump: null,
    amount_note: "都の支援（1時間150円）に加え、港区独自の上乗せ補助あり（詳細は区窓口で確認）",
    apply_method: "港区役所子ども家庭支援センターに申請",
    apply_url: "https://www.city.minato.tokyo.jp/kosodate/index.html",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: 0,
      child_age_max_months: 35,
      birth_order_min: null,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: null,
    }],
  },
  {
    id: "seed-027",
    layer: "ward",
    prefecture: "東京都",
    ward: "港区",
    name: "港区 産後ケア事業",
    category: "育児サービス",
    summary: "産後4ヶ月未満の母子を対象に助産院等でのケアを補助（最大7日間）",
    description: "港区では産後4ヶ月未満の母子を対象に、助産院・医療機関等での産後ケア（ショートステイ・デイサービス）を補助。区民は最大7日間利用可能で、利用料の大半を港区が補助（1日あたりの自己負担：デイ約1,500円・ショートステイ約3,000円程度）。",
    amount_monthly: null,
    amount_lump: null,
    amount_note: "最大7日間利用可（自己負担：デイ約1,500円・宿泊約3,000円程度）",
    apply_method: "港区保健センターまたは子ども家庭支援センターへ相談・申請",
    apply_url: "https://www.city.minato.tokyo.jp/kosodate/index.html",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: 0,
      child_age_max_months: 4,
      birth_order_min: null,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: null,
    }],
  },
  {
    id: "seed-028",
    layer: "ward",
    prefecture: "東京都",
    ward: "品川区",
    name: "品川区 私立幼稚園就園奨励費補助金",
    category: "保育・教育",
    summary: "私立幼稚園等に通う3〜5歳の子どもの保育料を区が補助",
    description: "品川区では国の幼児教育無償化（月25,700円上限）に加えて、品川区独自の補助を実施。私立幼稚園・認定こども園（幼稚園型）に通う3〜5歳の子どもを対象に、保育料の一部を品川区が上乗せ補助する。",
    amount_monthly: null,
    amount_lump: null,
    amount_note: "国の無償化（月最大25,700円）に加え、品川区が独自に上乗せ補助",
    apply_method: "在籍する幼稚園等を通じて申請（毎年度更新）",
    apply_url: "https://www.city.shinagawa.tokyo.jp/PC/kosodate/index.html",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: 36,
      child_age_max_months: 71,
      birth_order_min: null,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: null,
    }],
  },
  {
    id: "seed-029",
    layer: "ward",
    prefecture: "東京都",
    ward: "品川区",
    name: "品川区 電動アシスト自転車等購入費補助",
    category: "物品・生活支援",
    summary: "子育て世帯が電動アシスト自転車を購入する際に購入費の1/2（上限2万円）を補助",
    description: "品川区では18歳未満の子どもがいる世帯（子育て世帯）を対象に、電動アシスト自転車（チャイルドシート装着可能なもの・3人乗り対応含む）の購入費の1/2相当（上限20,000円）を補助。安全な子どもの送迎手段確保を支援する品川区独自の施策。",
    amount_monthly: null,
    amount_lump: 20000,
    amount_note: "購入費の1/2を補助（上限20,000円）。先着順のため早めに申請を",
    apply_method: "品川区役所子育て支援課の窓口に購入前に申請（レシートまたは領収書が必要）",
    apply_url: "https://www.city.shinagawa.tokyo.jp/PC/kosodate/index.html",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: 0,
      child_age_max_months: 215,
      birth_order_min: null,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: null,
    }],
  },
  {
    id: "seed-030",
    layer: "ward",
    prefecture: "東京都",
    ward: "品川区",
    name: "品川区 産後ケア事業",
    category: "育児サービス",
    summary: "産後間もない母子を対象に、助産師等によるケアをほぼ無料で受けられる",
    description: "品川区では産後間もない母子を対象に、助産院・医療機関等での産後ケア（デイサービス・ショートステイ）を補助。身体的回復の支援・授乳指導・育児相談等を実施。品川区民は利用料の大半を区が負担し、自己負担は1日数百円〜数千円程度。",
    amount_monthly: null,
    amount_lump: null,
    amount_note: "自己負担を大幅軽減（デイサービス・ショートステイ利用可、産後概ね4ヶ月未満）",
    apply_method: "品川区保健センターへ相談・申請（産後概ね4ヶ月未満）",
    apply_url: "https://www.city.shinagawa.tokyo.jp/PC/kosodate/index.html",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: 0,
      child_age_max_months: 4,
      birth_order_min: null,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: null,
    }],
  },
  {
    id: "seed-031",
    layer: "ward",
    prefecture: "東京都",
    ward: "目黒区",
    name: "目黒区 私立幼稚園就園奨励費補助",
    category: "保育・教育",
    summary: "私立幼稚園等に通う3〜5歳の保育料を区が補助",
    description: "目黒区では国の幼児教育無償化に加えて、目黒区独自の上乗せ補助を実施。私立幼稚園・認定こども園（幼稚園型）等に通う3〜5歳の子どもを対象に、保育料の一部を目黒区が補助する。所得に応じて補助額が変わる場合あり。",
    amount_monthly: null,
    amount_lump: null,
    amount_note: "国の無償化（月最大25,700円）に加え、目黒区が独自に上乗せ補助",
    apply_method: "在籍する幼稚園等を通じて申請",
    apply_url: "https://www.city.meguro.tokyo.jp/kosodate/index.html",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: 36,
      child_age_max_months: 71,
      birth_order_min: null,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: null,
    }],
  },
  {
    id: "seed-032",
    layer: "ward",
    prefecture: "東京都",
    ward: "目黒区",
    name: "目黒区 ベビーシッター利用支援",
    category: "育児サービス",
    summary: "都の支援（1時間150円）に加え、目黒区独自でベビーシッター利用料を補助",
    description: "東京都のベビーシッター利用支援事業（1時間150円）に加えて、目黒区独自の補助を実施。認可保育所等に入所できていない0〜2歳の乳幼児を持つ家庭を対象に、ベビーシッター利用料をさらに軽減する。",
    amount_monthly: null,
    amount_lump: null,
    amount_note: "都の支援（1時間150円）に加え、目黒区独自の上乗せ補助あり",
    apply_method: "目黒区役所子育て支援課に申請",
    apply_url: "https://www.city.meguro.tokyo.jp/kosodate/index.html",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: 0,
      child_age_max_months: 35,
      birth_order_min: null,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: null,
    }],
  },
  {
    id: "seed-033",
    layer: "ward",
    prefecture: "東京都",
    ward: "目黒区",
    name: "目黒区 産後ケア支援事業",
    category: "育児サービス",
    summary: "産後の母子に助産師等によるケアを補助（デイ・ショートステイ）",
    description: "目黒区では産後間もない母子（概ね産後4ヶ月未満）を対象に、助産院等での産後ケアを補助。授乳支援・育児相談・母体回復支援を行う。利用料の大半を区が負担し、デイサービス・ショートステイ型を低負担で利用可能。",
    amount_monthly: null,
    amount_lump: null,
    amount_note: "大幅な自己負担軽減（デイ・ショートステイ利用可、産後4ヶ月未満）",
    apply_method: "目黒区保健センターに相談・申請",
    apply_url: "https://www.city.meguro.tokyo.jp/kosodate/index.html",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: 0,
      child_age_max_months: 4,
      birth_order_min: null,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: null,
    }],
  },
  {
    id: "seed-034",
    layer: "ward",
    prefecture: "東京都",
    ward: "江東区",
    name: "江東区 私立幼稚園就園奨励費補助",
    category: "保育・教育",
    summary: "私立幼稚園等に通う3〜5歳の保育料を区が補助",
    description: "江東区では国の幼児教育無償化に加えて、江東区独自の補助を実施。私立幼稚園・認定こども園等に通う3〜5歳の子どもを対象に保育料の一部を補助する。所得に応じて補助額が変わる場合あり。",
    amount_monthly: null,
    amount_lump: null,
    amount_note: "国の無償化に加え、江東区が独自に上乗せ補助（所得に応じて異なる）",
    apply_method: "在籍する幼稚園等を通じて申請（毎年度更新）",
    apply_url: "https://www.city.koto.lg.jp/390101/kosodate/index.html",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: 36,
      child_age_max_months: 71,
      birth_order_min: null,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: null,
    }],
  },
  {
    id: "seed-035",
    layer: "ward",
    prefecture: "東京都",
    ward: "江東区",
    name: "江東区 電動アシスト自転車等購入費補助",
    category: "物品・生活支援",
    summary: "子育て世帯が電動アシスト自転車（3人乗り対応含む）購入時に購入費の一部を補助",
    description: "江東区では18歳未満の子どもがいる世帯（子育て世帯）を対象に、電動アシスト付自転車（チャイルドシート対応・3人乗り対応等）の購入費の一部を補助。安全な子どもの送迎手段確保を目的とした江東区の支援策。",
    amount_monthly: null,
    amount_lump: 20000,
    amount_note: "購入費の一部補助（上限20,000円、先着順のため予算が無くなり次第終了）",
    apply_method: "江東区役所窓口に購入前に申請（予算に限りあり、年度早めに申請を）",
    apply_url: "https://www.city.koto.lg.jp/390101/kosodate/index.html",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: 0,
      child_age_max_months: 215,
      birth_order_min: null,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: null,
    }],
  },
  {
    id: "seed-036",
    layer: "ward",
    prefecture: "東京都",
    ward: "江東区",
    name: "江東区 産後家庭支援員派遣事業",
    category: "育児サービス",
    summary: "産後の家庭に家庭支援員を派遣し、育児・家事を支援（所得に応じて実質無料〜）",
    description: "江東区では産後間もない（原則産後4ヶ月未満）家庭に、家庭支援員（ヘルパー）を派遣。育児支援・家事援助・育児相談などを行う。利用料は所得に応じた負担（低所得世帯は無料）。産後の孤立や育児不安を軽減するための支援。",
    amount_monthly: null,
    amount_lump: null,
    amount_note: "1時間あたり数百円〜（所得に応じた負担。低所得世帯は無料の場合あり）",
    apply_method: "江東区役所または子ども家庭支援センターに申請",
    apply_url: "https://www.city.koto.lg.jp/390101/kosodate/index.html",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: 0,
      child_age_max_months: 4,
      birth_order_min: null,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: null,
    }],
  },
  {
    id: "seed-037",
    layer: "ward",
    prefecture: "東京都",
    ward: "江戸川区",
    name: "江戸川区 乳児養育手当",
    category: "給付金・手当",
    summary: "0歳（1歳未満）の乳児を在宅で養育している保護者に月13,000円を支給",
    description: "江戸川区独自の子育て支援手当。1歳未満の乳児を認可保育所・認定こども園等に入所させず在宅で養育している保護者に、月13,000円を支給する。所得制限あり（扶養義務者の前年所得が一定以下）。江戸川区の手厚い子育て支援の代表的な制度。",
    amount_monthly: 13000,
    amount_lump: null,
    amount_note: "月13,000円（最長11ヶ月間）= 年間最大143,000円の支給",
    apply_method: "江戸川区役所子育て支援課に出生後速やかに申請（認可保育所等に入所していないことが条件）",
    apply_url: "https://www.city.edogawa.tokyo.jp/kosodate/index.html",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: 0,
      child_age_max_months: 11,
      birth_order_min: null,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: 700,
    }],
  },
  {
    id: "seed-038",
    layer: "ward",
    prefecture: "東京都",
    ward: "江戸川区",
    name: "江戸川区 私立幼稚園就園奨励費補助",
    category: "保育・教育",
    summary: "私立幼稚園等に通う3〜5歳の保育料を区が補助",
    description: "江戸川区では国の幼児教育無償化に加えて、江戸川区独自の上乗せ補助を実施。私立幼稚園・認定こども園（幼稚園型）等に通う3〜5歳の子どもを対象に、保育料の一部を補助する。",
    amount_monthly: null,
    amount_lump: null,
    amount_note: "国の無償化に加え、江戸川区が独自に上乗せ補助",
    apply_method: "在籍する幼稚園等を通じて申請（毎年度更新）",
    apply_url: "https://www.city.edogawa.tokyo.jp/kosodate/index.html",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: 36,
      child_age_max_months: 71,
      birth_order_min: null,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: null,
    }],
  },
  {
    id: "seed-039",
    layer: "ward",
    prefecture: "東京都",
    ward: "江戸川区",
    name: "江戸川区 電動アシスト自転車等購入費補助",
    category: "物品・生活支援",
    summary: "子育て世帯が電動アシスト自転車を購入する際に購入費の1/2（上限2万円）を補助",
    description: "江戸川区では18歳未満の子どもがいる世帯（子育て世帯）を対象に、電動アシスト付自転車の購入費の一部を補助。チャイルドシート付きや3人乗り対応のものも対象。子育て世帯の安全な移動手段確保を目的とした江戸川区独自の支援策。",
    amount_monthly: null,
    amount_lump: 20000,
    amount_note: "購入費の1/2補助（上限20,000円）先着順。年度ごとに予算が設定されるため早めに申請を",
    apply_method: "江戸川区役所子育て支援課の窓口に購入前に申請",
    apply_url: "https://www.city.edogawa.tokyo.jp/kosodate/index.html",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: 0,
      child_age_max_months: 215,
      birth_order_min: null,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: null,
    }],
  },
  {
    id: "seed-040",
    layer: "ward",
    prefecture: "東京都",
    ward: "千代田区",
    name: "千代田区 子ども医療費助成",
    category: "医療費助成",
    summary: "高校生まで医療費が無料（所得制限なし）",
    description: "千代田区では0歳から高校卒業（18歳到達後の3月31日）まで医療費（保険診療内の入院・通院）が無料。千代田区は全国有数の高所得エリアながら医療費は完全無料で所得制限なし。",
    amount_monthly: null,
    amount_lump: null,
    amount_note: "高校生まで保険診療内の医療費が0円",
    apply_method: "転入時または出生届提出時に千代田区役所へ申請",
    apply_url: "https://www.city.chiyoda.lg.jp/kosei/kosodate/index.html",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: 0,
      child_age_max_months: 215,
      birth_order_min: null,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: null,
    }],
  },
  {
    id: "seed-041",
    layer: "ward",
    prefecture: "東京都",
    ward: "中央区",
    name: "中央区 子ども医療費助成",
    category: "医療費助成",
    summary: "高校生まで医療費が無料（所得制限なし）",
    description: "中央区では0歳から高校卒業まで医療費（保険診療内）が無料。中央区は日本橋・銀座エリアを擁し、子育て支援にも力を入れている。",
    amount_monthly: null,
    amount_lump: null,
    amount_note: "高校生まで保険診療内の医療費が0円",
    apply_method: "転入時または出生届提出時に中央区役所へ申請",
    apply_url: "https://www.city.chuo.lg.jp/kosodate/index.html",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: 0,
      child_age_max_months: 215,
      birth_order_min: null,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: null,
    }],
  },
  {
    id: "seed-042",
    layer: "ward",
    prefecture: "東京都",
    ward: "新宿区",
    name: "新宿区 子ども医療費助成",
    category: "医療費助成",
    summary: "高校生まで医療費が無料（所得制限なし）",
    description: "新宿区では0歳から高校卒業（18歳到達後の3月31日）まで医療費（保険診療内の入院・通院）が無料。多様な家族構成の子育て世帯を支援。",
    amount_monthly: null,
    amount_lump: null,
    amount_note: "高校生まで保険診療内の医療費が0円",
    apply_method: "転入時または出生届提出時に新宿区役所へ申請",
    apply_url: "https://www.city.shinjuku.lg.jp/kodomo/index.html",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: 0,
      child_age_max_months: 215,
      birth_order_min: null,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: null,
    }],
  },
  {
    id: "seed-043",
    layer: "ward",
    prefecture: "東京都",
    ward: "文京区",
    name: "文京区 子ども医療費助成",
    category: "医療費助成",
    summary: "高校生まで医療費が無料（所得制限なし）",
    description: "文京区では0歳から高校卒業まで医療費（保険診療内）が無料。東大・医療機関が多く集まる文京区は子育て環境も充実している。",
    amount_monthly: null,
    amount_lump: null,
    amount_note: "高校生まで保険診療内の医療費が0円",
    apply_method: "転入時または出生届提出時に文京区役所へ申請",
    apply_url: "https://www.city.bunkyo.lg.jp/kosodate/index.html",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: 0,
      child_age_max_months: 215,
      birth_order_min: null,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: null,
    }],
  },
  {
    id: "seed-044",
    layer: "ward",
    prefecture: "東京都",
    ward: "台東区",
    name: "台東区 子ども医療費助成",
    category: "医療費助成",
    summary: "高校生まで医療費が無料（所得制限なし）",
    description: "台東区では0歳から高校卒業（18歳到達後の3月31日）まで医療費（保険診療内の入院・通院）が無料。上野・浅草エリアを持つ台東区が子育て世帯を全面支援。",
    amount_monthly: null,
    amount_lump: null,
    amount_note: "高校生まで保険診療内の医療費が0円",
    apply_method: "転入時または出生届提出時に台東区役所へ申請",
    apply_url: "https://www.city.taito.lg.jp/kosodate/index.html",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: 0,
      child_age_max_months: 215,
      birth_order_min: null,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: null,
    }],
  },
  {
    id: "seed-045",
    layer: "ward",
    prefecture: "東京都",
    ward: "墨田区",
    name: "墨田区 子ども医療費助成",
    category: "医療費助成",
    summary: "高校生まで医療費が無料（所得制限なし）",
    description: "墨田区では0歳から高校卒業まで医療費（保険診療内）が無料。スカイツリーで有名な墨田区は住みやすい子育て環境を整備している。",
    amount_monthly: null,
    amount_lump: null,
    amount_note: "高校生まで保険診療内の医療費が0円",
    apply_method: "転入時または出生届提出時に墨田区役所へ申請",
    apply_url: "https://www.city.sumida.lg.jp/kosodate/index.html",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: 0,
      child_age_max_months: 215,
      birth_order_min: null,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: null,
    }],
  },
  {
    id: "seed-046",
    layer: "ward",
    prefecture: "東京都",
    ward: "大田区",
    name: "大田区 子ども医療費助成",
    category: "医療費助成",
    summary: "高校生まで医療費が無料（所得制限なし）",
    description: "大田区では0歳から高校卒業（18歳到達後の3月31日）まで医療費（保険診療内の入院・通院）が無料。23区最大の面積を持つ大田区が子育て世帯を支援。",
    amount_monthly: null,
    amount_lump: null,
    amount_note: "高校生まで保険診療内の医療費が0円",
    apply_method: "転入時または出生届提出時に大田区役所へ申請",
    apply_url: "https://www.city.ota.tokyo.jp/seikatsu/kodomo/index.html",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: 0,
      child_age_max_months: 215,
      birth_order_min: null,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: null,
    }],
  },
  {
    id: "seed-047",
    layer: "ward",
    prefecture: "東京都",
    ward: "世田谷区",
    name: "世田谷区 子ども医療費助成",
    category: "医療費助成",
    summary: "高校生まで医療費が無料（所得制限なし）",
    description: "世田谷区では0歳から高校卒業まで医療費（保険診療内）が無料。23区最大の人口を持つ世田谷区は子育て施策も充実しており、ファミリー世帯に人気のエリア。",
    amount_monthly: null,
    amount_lump: null,
    amount_note: "高校生まで保険診療内の医療費が0円",
    apply_method: "転入時または出生届提出時に世田谷区役所へ申請",
    apply_url: "https://www.city.setagaya.lg.jp/mokuji/kodomo/index.html",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: 0,
      child_age_max_months: 215,
      birth_order_min: null,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: null,
    }],
  },
  {
    id: "seed-048",
    layer: "ward",
    prefecture: "東京都",
    ward: "渋谷区",
    name: "渋谷区 子ども医療費助成",
    category: "医療費助成",
    summary: "高校生まで医療費が無料（所得制限なし）",
    description: "渋谷区では0歳から高校卒業まで医療費（保険診療内）が無料。保育料無料化でも有名な渋谷区は医療費も完全無料で子育て世帯を強力支援。",
    amount_monthly: null,
    amount_lump: null,
    amount_note: "高校生まで保険診療内の医療費が0円",
    apply_method: "転入時または出生届提出時に渋谷区役所へ申請",
    apply_url: "https://www.city.shibuya.tokyo.jp/kodomo/index.html",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: 0,
      child_age_max_months: 215,
      birth_order_min: null,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: null,
    }],
  },
  {
    id: "seed-049",
    layer: "ward",
    prefecture: "東京都",
    ward: "中野区",
    name: "中野区 子ども医療費助成",
    category: "医療費助成",
    summary: "高校生まで医療費が無料（所得制限なし）",
    description: "中野区では0歳から高校卒業まで医療費（保険診療内の入院・通院）が無料。交通利便性の高い中野区が子育て支援も充実。",
    amount_monthly: null,
    amount_lump: null,
    amount_note: "高校生まで保険診療内の医療費が0円",
    apply_method: "転入時または出生届提出時に中野区役所へ申請",
    apply_url: "https://www.city.tokyo-nakano.lg.jp/dept/400000/index.html",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: 0,
      child_age_max_months: 215,
      birth_order_min: null,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: null,
    }],
  },
  {
    id: "seed-050",
    layer: "ward",
    prefecture: "東京都",
    ward: "杉並区",
    name: "杉並区 子ども医療費助成",
    category: "医療費助成",
    summary: "高校生まで医療費が無料（所得制限なし）",
    description: "杉並区では0歳から高校卒業まで医療費（保険診療内）が無料。住宅街として人気の杉並区は子育て環境も整っており、ファミリー向けの施策が充実。",
    amount_monthly: null,
    amount_lump: null,
    amount_note: "高校生まで保険診療内の医療費が0円",
    apply_method: "転入時または出生届提出時に杉並区役所へ申請",
    apply_url: "https://www.city.suginami.tokyo.jp/guide/kosodate/index.html",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: 0,
      child_age_max_months: 215,
      birth_order_min: null,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: null,
    }],
  },
  {
    id: "seed-051",
    layer: "ward",
    prefecture: "東京都",
    ward: "豊島区",
    name: "豊島区 子ども医療費助成",
    category: "医療費助成",
    summary: "高校生まで医療費が無料（所得制限なし）",
    description: "豊島区では0歳から高校卒業まで医療費（保険診療内）が無料。池袋を中心とする豊島区は「消滅可能性都市」からの再生として子育て支援に積極的に取り組む。",
    amount_monthly: null,
    amount_lump: null,
    amount_note: "高校生まで保険診療内の医療費が0円",
    apply_method: "転入時または出生届提出時に豊島区役所へ申請",
    apply_url: "https://www.city.toshima.lg.jp/1/kosodate/index.html",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: 0,
      child_age_max_months: 215,
      birth_order_min: null,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: null,
    }],
  },
  {
    id: "seed-052",
    layer: "ward",
    prefecture: "東京都",
    ward: "北区",
    name: "北区 子ども医療費助成",
    category: "医療費助成",
    summary: "高校生まで医療費が無料（所得制限なし）",
    description: "北区では0歳から高校卒業（18歳到達後の3月31日）まで医療費（保険診療内の入院・通院）が無料。赤羽などの住宅エリアが広がる北区が子育て世帯を支援。",
    amount_monthly: null,
    amount_lump: null,
    amount_note: "高校生まで保険診療内の医療費が0円",
    apply_method: "転入時または出生届提出時に北区役所へ申請",
    apply_url: "https://www.city.kita.tokyo.jp/k-kosodate/index.html",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: 0,
      child_age_max_months: 215,
      birth_order_min: null,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: null,
    }],
  },
  {
    id: "seed-053",
    layer: "ward",
    prefecture: "東京都",
    ward: "荒川区",
    name: "荒川区 子ども医療費助成",
    category: "医療費助成",
    summary: "高校生まで医療費が無料（所得制限なし）",
    description: "荒川区では0歳から高校卒業まで医療費（保険診療内）が無料。都電荒川線（さくらトラム）沿いの下町情緒あふれる荒川区が子育て世帯を支援。",
    amount_monthly: null,
    amount_lump: null,
    amount_note: "高校生まで保険診療内の医療費が0円",
    apply_method: "転入時または出生届提出時に荒川区役所へ申請",
    apply_url: "https://www.city.arakawa.tokyo.jp/kosodate/index.html",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: 0,
      child_age_max_months: 215,
      birth_order_min: null,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: null,
    }],
  },
  {
    id: "seed-054",
    layer: "ward",
    prefecture: "東京都",
    ward: "板橋区",
    name: "板橋区 子ども医療費助成",
    category: "医療費助成",
    summary: "高校生まで医療費が無料（所得制限なし）",
    description: "板橋区では0歳から高校卒業（18歳到達後の3月31日）まで医療費（保険診療内の入院・通院）が無料。豊かな自然と住宅地が広がる板橋区が子育て世帯を支援。",
    amount_monthly: null,
    amount_lump: null,
    amount_note: "高校生まで保険診療内の医療費が0円",
    apply_method: "転入時または出生届提出時に板橋区役所へ申請",
    apply_url: "https://www.city.itabashi.tokyo.jp/kosodate/index.html",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: 0,
      child_age_max_months: 215,
      birth_order_min: null,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: null,
    }],
  },
  {
    id: "seed-055",
    layer: "ward",
    prefecture: "東京都",
    ward: "練馬区",
    name: "練馬区 子ども医療費助成",
    category: "医療費助成",
    summary: "高校生まで医療費が無料（所得制限なし）",
    description: "練馬区では0歳から高校卒業まで医療費（保険診療内）が無料。農地と住宅が共存する練馬区は子育て環境に優れ、多くのファミリーが暮らす。",
    amount_monthly: null,
    amount_lump: null,
    amount_note: "高校生まで保険診療内の医療費が0円",
    apply_method: "転入時または出生届提出時に練馬区役所へ申請",
    apply_url: "https://www.nerima-kodomoegao.jp/",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: 0,
      child_age_max_months: 215,
      birth_order_min: null,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: null,
    }],
  },
  {
    id: "seed-056",
    layer: "ward",
    prefecture: "東京都",
    ward: "足立区",
    name: "足立区 子ども医療費助成",
    category: "医療費助成",
    summary: "高校生まで医療費が無料（所得制限なし）",
    description: "足立区では0歳から高校卒業（18歳到達後の3月31日）まで医療費（保険診療内の入院・通院）が無料。出産祝い金も手厚く、子育て世帯に優しい足立区。",
    amount_monthly: null,
    amount_lump: null,
    amount_note: "高校生まで保険診療内の医療費が0円",
    apply_method: "転入時または出生届提出時に足立区役所へ申請",
    apply_url: "https://www.city.adachi.tokyo.jp/kosodate/index.html",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: 0,
      child_age_max_months: 215,
      birth_order_min: null,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: null,
    }],
  },
  {
    id: "seed-057",
    layer: "ward",
    prefecture: "東京都",
    ward: "葛飾区",
    name: "葛飾区 子ども医療費助成",
    category: "医療費助成",
    summary: "高校生まで医療費が無料（所得制限なし）",
    description: "葛飾区では0歳から高校卒業まで医療費（保険診療内）が無料。東京東部の下町情緒あふれる葛飾区が子育て世帯を全面支援。",
    amount_monthly: null,
    amount_lump: null,
    amount_note: "高校生まで保険診療内の医療費が0円",
    apply_method: "転入時または出生届提出時に葛飾区役所へ申請",
    apply_url: "https://www.city.katsushika.lg.jp/kosodate/index.html",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: 0,
      child_age_max_months: 215,
      birth_order_min: null,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: null,
    }],
  },
  {
    id: "seed-058",
    layer: "ward",
    prefecture: "東京都",
    ward: "千代田区",
    name: "千代田区 出産お祝い金",
    category: "一時金",
    summary: "千代田区在住の子どもが生まれた家庭に出産お祝い金を支給",
    description: "千代田区では区内在住で出産した家庭に出産お祝い金を支給。第1子：100,000円、第2子以降：200,000円と、子どもが増えるほど支援が手厚くなる千代田区独自の制度。",
    amount_monthly: null,
    amount_lump: 100000,
    amount_note: "第1子：100,000円 ／ 第2子以降：200,000円",
    apply_method: "出生届提出後、千代田区役所子ども支援課に申請（出生後6ヶ月以内）",
    apply_url: "https://www.city.chiyoda.lg.jp/kosei/kosodate/index.html",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: 0,
      child_age_max_months: 6,
      birth_order_min: null,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: null,
    }],
  },
  {
    id: "seed-059",
    layer: "ward",
    prefecture: "東京都",
    ward: "中央区",
    name: "中央区 出産支援給付金",
    category: "一時金",
    summary: "中央区在住で出産した家庭に給付金を支給（区独自の上乗せあり）",
    description: "中央区では国の「出産・子育て応援交付金」（計10万円）に加えて、中央区独自の出産支援給付金を実施。妊娠届・出生届の際に支給される給付金で、育児用品や食料品などに使えるカタログギフトや現金で支給。",
    amount_monthly: null,
    amount_lump: 100000,
    amount_note: "国の交付金10万円に加え、中央区独自の給付金あり（詳細は区窓口で確認）",
    apply_method: "妊娠届提出時・出生届提出時に中央区役所で案内",
    apply_url: "https://www.city.chuo.lg.jp/kosodate/index.html",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: 0,
      child_age_max_months: 6,
      birth_order_min: null,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: null,
    }],
  },
  {
    id: "seed-060",
    layer: "ward",
    prefecture: "東京都",
    ward: "渋谷区",
    name: "渋谷区 保育料完全無料化（0〜5歳・全員対象）",
    category: "保育・教育",
    summary: "0〜5歳の全子どもの認可保育所等の保育料が所得に関係なく無料（2020年〜）",
    description: "渋谷区は2020年4月から、国の幼児教育無償化（3〜5歳）に加え、0〜2歳についても全ての子どもの認可保育所・認定こども園等の保育料を無料化。所得制限なし、第1子から全員対象。日本初の0〜5歳全年齢無料化を実現した先進的な制度。認可外保育施設も最大月77,000円まで補助あり。",
    amount_monthly: null,
    amount_lump: null,
    amount_note: "0〜5歳全員の認可保育所等の保育料が完全無料（所得・世帯構成に関係なし）",
    apply_method: "保育所入所申請時に自動適用（0〜2歳は区の認定が必要）",
    apply_url: "https://www.city.shibuya.tokyo.jp/kodomo/index.html",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: 0,
      child_age_max_months: 71,
      birth_order_min: null,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: null,
    }],
  },
  {
    id: "seed-061",
    layer: "ward",
    prefecture: "東京都",
    ward: "世田谷区",
    name: "世田谷区 電動アシスト自転車等購入費補助",
    category: "物品・生活支援",
    summary: "子育て世帯の電動アシスト自転車購入を補助（上限2万円）",
    description: "世田谷区では18歳未満の子どもがいる世帯（子育て世帯）を対象に、電動アシスト付自転車（チャイルドシート装着可・3人乗り対応含む）の購入費の一部を補助。坂道の多い世田谷で安全な送迎手段確保を支援。",
    amount_monthly: null,
    amount_lump: 20000,
    amount_note: "購入費の一部補助（上限20,000円）先着順",
    apply_method: "世田谷区役所窓口で購入前に申請",
    apply_url: "https://www.city.setagaya.lg.jp/mokuji/kodomo/index.html",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: 0,
      child_age_max_months: 215,
      birth_order_min: null,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: null,
    }],
  },
  {
    id: "seed-062",
    layer: "ward",
    prefecture: "東京都",
    ward: "練馬区",
    name: "練馬区 電動アシスト自転車等購入費補助",
    category: "物品・生活支援",
    summary: "子育て世帯の電動アシスト自転車購入を補助（上限2万円）",
    description: "練馬区では18歳未満の子どもがいる世帯（子育て世帯）を対象に、電動アシスト付自転車（チャイルドシート対応・3人乗り対応含む）の購入費の一部を補助。広い練馬区での安全な送迎手段確保を支援。",
    amount_monthly: null,
    amount_lump: 20000,
    amount_note: "購入費の一部補助（上限20,000円）先着順",
    apply_method: "練馬区役所窓口で購入前に申請",
    apply_url: "https://www.nerima-kodomoegao.jp/",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: 0,
      child_age_max_months: 215,
      birth_order_min: null,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: null,
    }],
  },
  {
    id: "seed-063",
    layer: "ward",
    prefecture: "東京都",
    ward: "足立区",
    name: "足立区 出産祝い金",
    category: "一時金",
    summary: "区内在住の子どもが生まれた家庭に出産祝い金を支給（第3子以降は30万円）",
    description: "足立区では区内在住で出産した家庭に出産祝い金を支給。第1子：50,000円、第2子：100,000円、第3子以降：300,000円と、多子世帯に特に手厚い支援を実施。足立区の子育て支援策の中でも最も注目度が高い制度。",
    amount_monthly: null,
    amount_lump: 50000,
    amount_note: "第1子：50,000円 ／ 第2子：100,000円 ／ 第3子以降：300,000円",
    apply_method: "出生届提出後、足立区役所子ども支援課に申請",
    apply_url: "https://www.city.adachi.tokyo.jp/kosodate/index.html",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: 0,
      child_age_max_months: 6,
      birth_order_min: null,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: null,
    }],
  },
  {
    id: "seed-064",
    layer: "ward",
    prefecture: "東京都",
    ward: "文京区",
    name: "文京区 出産・子育て応援交付金",
    category: "一時金",
    summary: "妊娠届・出生届時に合計10万円相当の給付金またはギフトを支給",
    description: "文京区では国の「出産・子育て応援交付金」を実施。妊娠届時に5万円分、出生届後に5万円分（計10万円）のギフトカタログや育児用品を支給。ハーバード大学などとも連携した文京区ならではの子育て支援策。",
    amount_monthly: null,
    amount_lump: 100000,
    amount_note: "妊娠届時5万円 ＋ 出生時5万円（合計10万円）",
    apply_method: "妊娠届提出時に文京区役所で案内。出生後は別途申請が必要。",
    apply_url: "https://www.city.bunkyo.lg.jp/kosodate/index.html",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: 0,
      child_age_max_months: 6,
      birth_order_min: null,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: null,
    }],
  },
  {
    id: "seed-065",
    layer: "ward",
    prefecture: "東京都",
    ward: "大田区",
    name: "大田区 出産・子育て応援交付金",
    category: "一時金",
    summary: "妊娠届・出生届時に合計10万円相当の給付金・ギフトを支給",
    description: "大田区では国の「出産・子育て応援交付金」を実施。妊娠届時に5万円分、出生届後に5万円分（計10万円）のギフトカタログまたは現金相当を支給。羽田空港に隣接する大田区が子育て世帯を全力支援。",
    amount_monthly: null,
    amount_lump: 100000,
    amount_note: "妊娠届時5万円 ＋ 出生時5万円（合計10万円）",
    apply_method: "妊娠届提出時に大田区役所で案内",
    apply_url: "https://www.city.ota.tokyo.jp/seikatsu/kodomo/index.html",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: 0,
      child_age_max_months: 6,
      birth_order_min: null,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: null,
    }],
  },
  {
    id: "seed-066",
    layer: "ward",
    prefecture: "東京都",
    ward: "葛飾区",
    name: "葛飾区 出産・子育て応援交付金",
    category: "一時金",
    summary: "妊娠届・出生届時に合計10万円相当の給付金・ギフトを支給",
    description: "葛飾区では国の「出産・子育て応援交付金」を実施。妊娠届時に5万円分、出生届後に5万円分（計10万円）のギフトカタログまたは現金相当を支給。",
    amount_monthly: null,
    amount_lump: 100000,
    amount_note: "妊娠届時5万円 ＋ 出生時5万円（合計10万円）",
    apply_method: "妊娠届提出時に葛飾区役所で案内",
    apply_url: "https://www.city.katsushika.lg.jp/kosodate/index.html",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: 0,
      child_age_max_months: 6,
      birth_order_min: null,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: null,
    }],
  },
  {
    id: "seed-067",
    layer: "ward",
    prefecture: "東京都",
    ward: "台東区",
    name: "台東区 出産・子育て応援交付金",
    category: "一時金",
    summary: "妊娠届・出生届時に合計10万円相当の給付金・ギフトを支給",
    description: "台東区では国の「出産・子育て応援交付金」を実施。妊娠届時に5万円分、出生届後に5万円分（計10万円）のギフトカタログまたは現金相当を支給。伝統ある下町文化の台東区が子育て世帯を応援。",
    amount_monthly: null,
    amount_lump: 100000,
    amount_note: "妊娠届時5万円 ＋ 出生時5万円（合計10万円）",
    apply_method: "妊娠届提出時に台東区役所で案内",
    apply_url: "https://www.city.taito.lg.jp/kosodate/index.html",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: 0,
      child_age_max_months: 6,
      birth_order_min: null,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: null,
    }],
  },

  // ============================================================
  // 埼玉県レベル (pref)
  // ============================================================
  {
    id: "seed-068",
    layer: "pref",
    prefecture: "埼玉県",
    ward: null,
    name: "埼玉県 子ども医療費助成（通院・入院）",
    category: "医療費助成",
    summary: "0歳〜中学生まで医療費の自己負担を県が助成（市町村上乗せで18歳まで無料の地域多数）",
    description: "埼玉県の子ども医療費助成制度。0歳から中学校修了（15歳年度末）まで、保険診療の自己負担分を県が助成。和光市・川口市・所沢市など多くの市区町村が独自に上乗せして高校卒業（18歳年度末）まで無料化している。所得制限なし。",
    amount_monthly: null,
    amount_lump: null,
    amount_note: "保険診療内の医療費を助成（市町村上乗せで18歳まで無料の場合が多い）",
    apply_method: "転入時または出生届提出後、居住市区町村の窓口で申請（医療証が発行される）",
    apply_url: "https://www.pref.saitama.lg.jp/a0703/kodomo-iryouhi.html",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: 0,
      child_age_max_months: 215,
      birth_order_min: null,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: null,
    }],
  },
  {
    id: "seed-069",
    layer: "pref",
    prefecture: "埼玉県",
    ward: null,
    name: "埼玉県 不妊治療費助成事業",
    category: "一時金",
    summary: "体外受精・顕微授精等の特定不妊治療費を1回最大30万円助成（所得制限あり）",
    description: "埼玉県独自の不妊治療費助成。体外受精・顕微授精を対象に1回あたり最大30万円（県15万円＋市町村上乗せ分）を助成。夫婦合算の所得730万円未満が対象。通算5回まで利用可能。",
    amount_monthly: null,
    amount_lump: 300000,
    amount_note: "1回最大30万円（県15万円＋市町村上乗せ）、通算5回まで",
    apply_method: "治療後に居住市区町村の窓口または埼玉県へ申請",
    apply_url: "https://www.pref.saitama.lg.jp/a0704/funin-joseikin.html",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: null,
      child_age_max_months: null,
      birth_order_min: null,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: 730,
    }],
  },
  // ============================================================
  // 神奈川県レベル (pref)
  // ============================================================
  {
    id: "seed-070",
    layer: "pref",
    prefecture: "神奈川県",
    ward: null,
    name: "神奈川県 子ども医療費助成",
    category: "医療費助成",
    summary: "小学校修了まで医療費を県が助成。各市が上乗せし中学・高校まで無料にしている場合が多い",
    description: "神奈川県の子ども医療費助成制度。0歳から小学校修了（12歳年度末）まで保険診療の自己負担分を助成。川崎市・横浜市など多くの市が独自に上乗せして高校卒業（18歳年度末）まで無料化。所得制限なし。",
    amount_monthly: null,
    amount_lump: null,
    amount_note: "保険診療内の医療費を助成（市の上乗せで多くの地域が18歳まで無料）",
    apply_method: "転入時または出生届提出後、居住市の窓口で申請（医療証が発行される）",
    apply_url: "https://www.pref.kanagawa.jp/docs/v3k/cnt/f00041/",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: 0,
      child_age_max_months: 215,
      birth_order_min: null,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: null,
    }],
  },
  {
    id: "seed-071",
    layer: "pref",
    prefecture: "神奈川県",
    ward: null,
    name: "神奈川県 赤ちゃん誕生おめでとう事業",
    category: "育児サービス",
    summary: "出産後に保健師や助産師が自宅を訪問し、育児相談と各種サービスを案内",
    description: "神奈川県の産後支援事業。生後4ヶ月以内の赤ちゃんがいる全家庭を対象に、保健師・助産師が訪問して育児不安の解消や地域子育て支援サービスの紹介を行う。申請不要で市区町村が自動的に連絡。",
    amount_monthly: null,
    amount_lump: null,
    amount_note: "訪問による育児相談・情報提供（現物給付）",
    apply_method: "申請不要（各市が出生情報をもとに連絡）",
    apply_url: "https://www.pref.kanagawa.jp/docs/v3k/cnt/f00041/",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: 0,
      child_age_max_months: 4,
      birth_order_min: null,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: null,
    }],
  },
  // ============================================================
  // 千葉県レベル (pref)
  // ============================================================
  {
    id: "seed-072",
    layer: "pref",
    prefecture: "千葉県",
    ward: null,
    name: "千葉県 子どもの医療費助成",
    category: "医療費助成",
    summary: "中学校修了まで医療費を県が助成。市が上乗せして18歳まで無料の地域が多い",
    description: "千葉県の子ども医療費助成制度。0歳から中学校修了（15歳年度末）まで保険診療の医療費（入院・通院）を助成。船橋市・市川市・松戸市・流山市など多くの市が独自上乗せで18歳年度末まで無料化している。所得制限なし。",
    amount_monthly: null,
    amount_lump: null,
    amount_note: "保険診療内の医療費を助成（市の上乗せで多くの地域が18歳まで無料）",
    apply_method: "転入時または出生届提出後、居住市の窓口で申請",
    apply_url: "https://www.pref.chiba.lg.jp/shounin/kodomo/iryouhijosei.html",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: 0,
      child_age_max_months: 215,
      birth_order_min: null,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: null,
    }],
  },
  {
    id: "seed-073",
    layer: "pref",
    prefecture: "千葉県",
    ward: null,
    name: "千葉県 出産・子育て応援給付金",
    category: "一時金",
    summary: "妊娠届・出生届時に計10万円分のクーポンを支給（国の制度を千葉県が実施）",
    description: "国の「出産・子育て応援交付金」を千葉県が実施。妊娠届出時に5万円相当、出生後に5万円相当のギフトカタログ・クーポンを支給。伴走型相談支援もセットで提供。",
    amount_monthly: null,
    amount_lump: 100000,
    amount_note: "妊娠届時5万円 + 出生時5万円（合計10万円相当）",
    apply_method: "妊娠届出時に市の窓口で案内される。出生後は別途申請が必要",
    apply_url: "https://www.pref.chiba.lg.jp/shounin/kodomo/",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: 0,
      child_age_max_months: 6,
      birth_order_min: null,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: null,
    }],
  },
  // ============================================================
  // 茨城県レベル (pref)
  // ============================================================
  {
    id: "seed-074",
    layer: "pref",
    prefecture: "茨城県",
    ward: null,
    name: "茨城県 子ども医療費助成",
    category: "医療費助成",
    summary: "高校生まで医療費を県が助成。所得制限なし",
    description: "茨城県の子ども医療費助成制度。2022年10月から対象を高校生（18歳年度末）まで拡大。保険診療の入院・通院費を助成（一定の自己負担あり）。所得制限なし。市町村が独自に上乗せして完全無料にしている地域もある。",
    amount_monthly: null,
    amount_lump: null,
    amount_note: "高校生まで保険診療内の医療費を助成（窓口で一部自己負担の場合あり）",
    apply_method: "転入時または出生届提出後、居住市町村の窓口で申請（医療証が発行される）",
    apply_url: "https://www.pref.ibaraki.jp/hokenfukushi/kofuku/jido/kodomo-iryou.html",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: 0,
      child_age_max_months: 215,
      birth_order_min: null,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: null,
    }],
  },
  {
    id: "seed-075",
    layer: "pref",
    prefecture: "茨城県",
    ward: null,
    name: "茨城県 出産・子育て応援給付金",
    category: "一時金",
    summary: "妊娠届・出生届時に計10万円分のギフト券を支給",
    description: "国の「出産・子育て応援交付金」を茨城県が実施。妊娠届出時に5万円相当（いばらき出産・育児支援サービス利用券など）、出生後に5万円相当を支給。伴走型相談支援とセット提供。",
    amount_monthly: null,
    amount_lump: 100000,
    amount_note: "妊娠届時5万円 + 出生時5万円（合計10万円相当）",
    apply_method: "妊娠届出時に市町村窓口で申請。出生後は別途手続きが必要",
    apply_url: "https://www.pref.ibaraki.jp/hokenfukushi/kofuku/jido/",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: 0,
      child_age_max_months: 6,
      birth_order_min: null,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: null,
    }],
  },
  // ============================================================
  // 和光市 (埼玉県)
  // ============================================================
  {
    id: "seed-076",
    layer: "ward",
    prefecture: "埼玉県",
    ward: "和光市",
    name: "和光市 子ども医療費助成",
    category: "医療費助成",
    summary: "18歳まで医療費が無料（所得制限なし）",
    description: "和光市では埼玉県の助成に加え、市独自の上乗せにより0歳から高校卒業（18歳年度末）まで保険診療の医療費（入院・通院）が実質無料。所得制限なし。",
    amount_monthly: null,
    amount_lump: null,
    amount_note: "高校生まで保険診療内の医療費が0円",
    apply_method: "転入時または出生届提出後、和光市役所福祉部窓口で申請",
    apply_url: "https://www.city.wako.lg.jp/home/kurashi/kosodate/iryohi/",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: 0,
      child_age_max_months: 215,
      birth_order_min: null,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: null,
    }],
  },
  {
    id: "seed-077",
    layer: "ward",
    prefecture: "埼玉県",
    ward: "和光市",
    name: "和光市 出産祝い品支給",
    category: "一時金",
    summary: "和光市在住で出産した家庭に出産祝い品（育児用品等）を支給",
    description: "和光市では市内在住の出産家庭に対し、育児用品等の出産祝い品を支給。第1子・第2子・第3子以降で内容が異なり、第3子以降は特に手厚い。申請は出生後90日以内。",
    amount_monthly: null,
    amount_lump: 30000,
    amount_note: "第1・2子：3万円相当 / 第3子以降：5万円相当の育児用品",
    apply_method: "出生後90日以内に和光市役所こども福祉課へ申請",
    apply_url: "https://www.city.wako.lg.jp/home/kurashi/kosodate/",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: 0,
      child_age_max_months: 3,
      birth_order_min: null,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: null,
    }],
  },
  {
    id: "seed-078",
    layer: "ward",
    prefecture: "埼玉県",
    ward: "和光市",
    name: "和光市 産後ケア事業",
    category: "育児サービス",
    summary: "産後4ヶ月未満の母子を対象に助産院・病院でのショートステイ・デイケアを低負担で利用可能",
    description: "和光市の産後ケア事業。産後4ヶ月未満の母子を対象に、助産院・病院でのショートステイ（宿泊型）・デイサービス（通所型）を利用できる。授乳指導・育児相談・産後回復支援を提供。市民税非課税世帯は利用料が減額。",
    amount_monthly: null,
    amount_lump: null,
    amount_note: "ショートステイ：1泊7,000円（市負担後）/ デイサービス：3,500円（市負担後）",
    apply_method: "和光市役所こども福祉課へ事前申請（産後退院後すぐ利用可）",
    apply_url: "https://www.city.wako.lg.jp/home/kurashi/kosodate/",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: 0,
      child_age_max_months: 4,
      birth_order_min: null,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: null,
    }],
  },
  // ============================================================
  // 川口市 (埼玉県)
  // ============================================================
  {
    id: "seed-079",
    layer: "ward",
    prefecture: "埼玉県",
    ward: "川口市",
    name: "川口市 子ども医療費助成",
    category: "医療費助成",
    summary: "18歳まで医療費が無料（所得制限なし）",
    description: "川口市では埼玉県の助成に独自の上乗せをして、0歳から高校卒業（18歳年度末）まで保険診療の医療費（入院・通院）が実質無料。所得制限なし。",
    amount_monthly: null,
    amount_lump: null,
    amount_note: "高校生まで保険診療内の医療費が実質0円",
    apply_method: "転入時または出生届提出後、川口市役所または各出張所で申請",
    apply_url: "https://www.city.kawaguchi.lg.jp/soshiki/01080/010801/006/6604.html",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: 0,
      child_age_max_months: 215,
      birth_order_min: null,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: null,
    }],
  },
  {
    id: "seed-080",
    layer: "ward",
    prefecture: "埼玉県",
    ward: "川口市",
    name: "川口市 出産・子育て応援給付金",
    category: "一時金",
    summary: "妊娠届・出生届時に計10万円相当のギフトを支給（伴走型支援とセット）",
    description: "国の「出産・子育て応援交付金」を川口市が実施。妊娠届出時に5万円相当（妊婦向け用品・サービス）、出生後に5万円相当（育児用品・サービス）のギフトを支給。専任の相談員による伴走型支援もセット提供。",
    amount_monthly: null,
    amount_lump: 100000,
    amount_note: "妊娠届時5万円相当 + 出生時5万円相当（合計10万円）",
    apply_method: "妊娠届出時に川口市役所健康づくり課または各保健センターで案内される",
    apply_url: "https://www.city.kawaguchi.lg.jp/soshiki/01080/010801/",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: 0,
      child_age_max_months: 6,
      birth_order_min: null,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: null,
    }],
  },
  {
    id: "seed-081",
    layer: "ward",
    prefecture: "埼玉県",
    ward: "川口市",
    name: "川口市 第2子以降保育料軽減",
    category: "保育・教育",
    summary: "第2子は保育料半額、第3子以降は無料（市独自軽減）",
    description: "川口市では認可保育所・認定こども園の保育料について、国の無償化（3〜5歳）に加え、第2子は半額、第3子以降は無料の独自軽減を実施。0〜2歳も対象（所得制限あり）。",
    amount_monthly: null,
    amount_lump: null,
    amount_note: "第2子保育料半額・第3子以降無料（市の独自軽減）",
    apply_method: "川口市役所保育課または各区役所で入所申込",
    apply_url: "https://www.city.kawaguchi.lg.jp/soshiki/01080/010803/",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: 0,
      child_age_max_months: 71,
      birth_order_min: 2,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: null,
    }],
  },
  // ============================================================
  // 所沢市 (埼玉県)
  // ============================================================
  {
    id: "seed-082",
    layer: "ward",
    prefecture: "埼玉県",
    ward: "所沢市",
    name: "所沢市 子ども医療費助成",
    category: "医療費助成",
    summary: "18歳まで医療費が無料（所得制限なし）",
    description: "所沢市では埼玉県の助成に独自の上乗せをして、0歳から高校卒業（18歳年度末）まで保険診療の医療費（入院・通院）が実質無料。所得制限なし。",
    amount_monthly: null,
    amount_lump: null,
    amount_note: "高校生まで保険診療内の医療費が0円",
    apply_method: "転入時または出生届提出後、所沢市役所または各出張所で申請",
    apply_url: "https://www.city.tokorozawa.saitama.jp/kosodate/iryohi/",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: 0,
      child_age_max_months: 215,
      birth_order_min: null,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: null,
    }],
  },
  {
    id: "seed-083",
    layer: "ward",
    prefecture: "埼玉県",
    ward: "所沢市",
    name: "所沢市 出産・子育て応援給付金",
    category: "一時金",
    summary: "妊娠届・出生届時に計10万円相当のギフトを支給",
    description: "国の「出産・子育て応援交付金」を所沢市が実施。妊娠届出時に5万円、出生後に5万円相当のギフトカタログ・サービス券を支給。伴走型相談支援もセット提供。",
    amount_monthly: null,
    amount_lump: 100000,
    amount_note: "妊娠届時5万円 + 出生時5万円（合計10万円相当）",
    apply_method: "妊娠届出時に所沢市役所健康推進センターで案内される",
    apply_url: "https://www.city.tokorozawa.saitama.jp/kosodate/",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: 0,
      child_age_max_months: 6,
      birth_order_min: null,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: null,
    }],
  },
  {
    id: "seed-084",
    layer: "ward",
    prefecture: "埼玉県",
    ward: "所沢市",
    name: "所沢市 多子世帯保育料無償化",
    category: "保育・教育",
    summary: "第3子以降は年齢に関わらず保育料が無料（所沢市独自）",
    description: "所沢市独自の多子世帯保育料軽減。国の無償化（3〜5歳）に加え、所沢市では第3子以降（0〜2歳を含む）の保育所・認定こども園の保育料を全額無料にしている。所得制限なし。",
    amount_monthly: null,
    amount_lump: null,
    amount_note: "第3子以降の保育料が完全無料（0〜5歳すべて）",
    apply_method: "保育所入所申込時に自動適用（所沢市役所保育課で確認）",
    apply_url: "https://www.city.tokorozawa.saitama.jp/kosodate/hoiku/",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: 0,
      child_age_max_months: 71,
      birth_order_min: 3,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: null,
    }],
  },
  // ============================================================
  // 川崎市 (神奈川県)
  // ============================================================
  {
    id: "seed-085",
    layer: "ward",
    prefecture: "神奈川県",
    ward: "川崎市",
    name: "川崎市 子ども医療費助成",
    category: "医療費助成",
    summary: "18歳まで医療費が無料（所得制限なし）",
    description: "川崎市では神奈川県の助成に独自の上乗せをして、0歳から高校卒業（18歳年度末）まで保険診療の医療費（入院・通院）が実質無料。所得制限なし。",
    amount_monthly: null,
    amount_lump: null,
    amount_note: "高校生まで保険診療内の医療費が実質0円",
    apply_method: "転入時または出生届提出後、川崎市各区役所で申請",
    apply_url: "https://www.city.kawasaki.jp/350/page/0000013525.html",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: 0,
      child_age_max_months: 215,
      birth_order_min: null,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: null,
    }],
  },
  {
    id: "seed-086",
    layer: "ward",
    prefecture: "神奈川県",
    ward: "川崎市",
    name: "川崎市 産後ケア事業",
    category: "育児サービス",
    summary: "産後1年未満の母子を対象に、宿泊型・通所型の産後ケアを低負担で利用可能",
    description: "川崎市の産後ケア事業。産後1年未満の母子を対象に、助産所・病院でのショートステイ（最大7日間）・デイサービス（最大10回）を利用できる。授乳指導・沐浴指導・育児相談が受けられる。市民税非課税世帯は無料。",
    amount_monthly: null,
    amount_lump: null,
    amount_note: "ショートステイ：1泊4,000〜6,000円 / デイ：1回2,000〜3,000円（収入により異なる）",
    apply_method: "川崎市各区の保健センターまたはこども家庭センターへ申請",
    apply_url: "https://www.city.kawasaki.jp/350/page/0000062741.html",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: 0,
      child_age_max_months: 11,
      birth_order_min: null,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: null,
    }],
  },
  {
    id: "seed-087",
    layer: "ward",
    prefecture: "神奈川県",
    ward: "川崎市",
    name: "川崎市 出産・子育て応援給付金",
    category: "一時金",
    summary: "妊娠届・出生届時に計10万円相当のギフト券を支給",
    description: "国の「出産・子育て応援交付金」を川崎市が実施。妊娠届出時に5万円相当（ギフトカードまたはこども商品券）、出生後に5万円相当を支給。専任の相談員による伴走型支援もセット。",
    amount_monthly: null,
    amount_lump: 100000,
    amount_note: "妊娠届時5万円 + 出生時5万円（合計10万円）",
    apply_method: "妊娠届出時に川崎市各区役所窓口で申請",
    apply_url: "https://www.city.kawasaki.jp/350/page/0000143111.html",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: 0,
      child_age_max_months: 6,
      birth_order_min: null,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: null,
    }],
  },
  // ============================================================
  // 横浜市 (神奈川県)
  // ============================================================
  {
    id: "seed-088",
    layer: "ward",
    prefecture: "神奈川県",
    ward: "横浜市",
    name: "横浜市 子ども医療費助成",
    category: "医療費助成",
    summary: "18歳まで医療費が無料（所得制限なし）",
    description: "横浜市では神奈川県の助成に独自の上乗せをして、0歳から高校卒業（18歳年度末）まで保険診療の医療費（入院・通院）が実質無料。所得制限なし。",
    amount_monthly: null,
    amount_lump: null,
    amount_note: "高校生まで保険診療内の医療費が0円",
    apply_method: "転入時または出生届提出後、横浜市各区役所で申請",
    apply_url: "https://www.city.yokohama.lg.jp/kosodate-kyoiku/kosodate/shien/iryohi/",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: 0,
      child_age_max_months: 215,
      birth_order_min: null,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: null,
    }],
  },
  {
    id: "seed-089",
    layer: "ward",
    prefecture: "神奈川県",
    ward: "横浜市",
    name: "横浜市 出産・子育て応援給付金",
    category: "一時金",
    summary: "妊娠届・出生届時に計10万円相当のギフトを支給",
    description: "国の「出産・子育て応援交付金」を横浜市が実施。妊娠届出時に5万円相当、出生後に5万円相当のギフト（育児用品・食料品・サービス等から選択可能）を支給。横浜市独自のギフト選択肢も追加されている。",
    amount_monthly: null,
    amount_lump: 100000,
    amount_note: "妊娠届時5万円 + 出生時5万円（合計10万円）",
    apply_method: "妊娠届出時に横浜市各区役所窓口で案内される",
    apply_url: "https://www.city.yokohama.lg.jp/kosodate-kyoiku/kosodate/shien/ouen_kyuufukin.html",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: 0,
      child_age_max_months: 6,
      birth_order_min: null,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: null,
    }],
  },
  {
    id: "seed-090",
    layer: "ward",
    prefecture: "神奈川県",
    ward: "横浜市",
    name: "横浜市 産後ケア事業",
    category: "育児サービス",
    summary: "産後1年未満の母子を対象に宿泊・通所・訪問型産後ケアを低負担で提供",
    description: "横浜市の産後ケア事業。産後1年未満の母子を対象に、宿泊型（最大7日）・通所型（最大10回）・訪問型（最大4回）の産後ケアを提供。授乳・育児相談・産後回復を専門職がサポート。市民税非課税世帯は大幅減額。",
    amount_monthly: null,
    amount_lump: null,
    amount_note: "宿泊型：1泊5,000〜8,000円 / 通所型：1回2,500〜4,000円（収入により異なる）",
    apply_method: "横浜市各区の福祉保健センターまたはオンラインで申請",
    apply_url: "https://www.city.yokohama.lg.jp/kosodate-kyoiku/kosodate/shien/sango-care.html",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: 0,
      child_age_max_months: 11,
      birth_order_min: null,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: null,
    }],
  },
  {
    id: "seed-091",
    layer: "ward",
    prefecture: "神奈川県",
    ward: "横浜市",
    name: "横浜市 保育料軽減（第2・3子）",
    category: "保育・教育",
    summary: "第2子の保育料が半額、第3子以降が無料（横浜市独自軽減）",
    description: "横浜市では国の保育料無償化（3〜5歳）に加え、0〜2歳の多子世帯にも独自軽減を実施。第2子は同時在園の場合に半額、第3子以降は無料。ひとり親家庭も優遇措置あり。",
    amount_monthly: null,
    amount_lump: null,
    amount_note: "第2子保育料半額・第3子以降無料（0〜2歳も対象）",
    apply_method: "保育所入所申込時に自動判定（横浜市各区役所で確認）",
    apply_url: "https://www.city.yokohama.lg.jp/kosodate-kyoiku/kosodate/hoiku/",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: 0,
      child_age_max_months: 35,
      birth_order_min: 2,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: null,
    }],
  },
  // ============================================================
  // 船橋市 (千葉県)
  // ============================================================
  {
    id: "seed-092",
    layer: "ward",
    prefecture: "千葉県",
    ward: "船橋市",
    name: "船橋市 子ども医療費助成",
    category: "医療費助成",
    summary: "18歳まで医療費が無料（所得制限なし）",
    description: "船橋市では千葉県の助成に独自の上乗せをして、0歳から高校卒業（18歳年度末）まで保険診療の医療費（入院・通院）が実質無料。所得制限なし。",
    amount_monthly: null,
    amount_lump: null,
    amount_note: "高校生まで保険診療内の医療費が0円",
    apply_method: "転入時または出生届提出後、船橋市役所または各出張所で申請",
    apply_url: "https://www.city.funabashi.lg.jp/kosodate/iryohi/",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: 0,
      child_age_max_months: 215,
      birth_order_min: null,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: null,
    }],
  },
  {
    id: "seed-093",
    layer: "ward",
    prefecture: "千葉県",
    ward: "船橋市",
    name: "船橋市 出産・子育て応援給付金",
    category: "一時金",
    summary: "妊娠届・出生届時に計10万円相当のギフト・クーポンを支給",
    description: "国の「出産・子育て応援交付金」を船橋市が実施。妊娠届出時に5万円相当（こども商品券または育児用品）、出生後に5万円相当を支給。市内の子育て支援サービスと連携したギフトも選択可能。",
    amount_monthly: null,
    amount_lump: 100000,
    amount_note: "妊娠届時5万円 + 出生時5万円（合計10万円）",
    apply_method: "妊娠届出時に船橋市役所保健センターで案内される",
    apply_url: "https://www.city.funabashi.lg.jp/kosodate/",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: 0,
      child_age_max_months: 6,
      birth_order_min: null,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: null,
    }],
  },
  {
    id: "seed-094",
    layer: "ward",
    prefecture: "千葉県",
    ward: "船橋市",
    name: "船橋市 産後家庭支援ヘルパー派遣",
    category: "育児サービス",
    summary: "産後6ヶ月未満の家庭に育児・家事支援ヘルパーを1時間700円から派遣",
    description: "船橋市の産後家庭支援ヘルパー派遣事業。産後6ヶ月未満の産婦がいる家庭に、育児や家事を手伝うヘルパーを派遣。利用者負担は1時間700円（市が残額を補助）。最大100時間まで利用可能。多胎児の場合は200時間まで。",
    amount_monthly: null,
    amount_lump: null,
    amount_note: "1時間700円（市が補助。最大100時間・多胎は200時間）",
    apply_method: "船橋市役所保健センターへ申請（産後退院後すぐ利用可能）",
    apply_url: "https://www.city.funabashi.lg.jp/kosodate/sango/",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: 0,
      child_age_max_months: 6,
      birth_order_min: null,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: null,
    }],
  },
  // ============================================================
  // 市川市 (千葉県)
  // ============================================================
  {
    id: "seed-095",
    layer: "ward",
    prefecture: "千葉県",
    ward: "市川市",
    name: "市川市 子ども医療費助成",
    category: "医療費助成",
    summary: "18歳まで医療費が無料（所得制限なし）",
    description: "市川市では千葉県の助成に独自の上乗せをして、0歳から高校卒業（18歳年度末）まで保険診療の医療費（入院・通院）が実質無料。所得制限なし。",
    amount_monthly: null,
    amount_lump: null,
    amount_note: "高校生まで保険診療内の医療費が0円",
    apply_method: "転入時または出生届提出後、市川市役所または各窓口で申請",
    apply_url: "https://www.city.ichikawa.lg.jp/wel01/1111000003.html",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: 0,
      child_age_max_months: 215,
      birth_order_min: null,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: null,
    }],
  },
  {
    id: "seed-096",
    layer: "ward",
    prefecture: "千葉県",
    ward: "市川市",
    name: "市川市 出産・子育て応援給付金",
    category: "一時金",
    summary: "妊娠届・出生届時に計10万円相当のギフトを支給",
    description: "国の「出産・子育て応援交付金」を市川市が実施。妊娠届出時に5万円相当、出生後に5万円相当のギフトカタログ・サービス券を支給。伴走型相談支援とセット。",
    amount_monthly: null,
    amount_lump: 100000,
    amount_note: "妊娠届時5万円 + 出生時5万円（合計10万円）",
    apply_method: "妊娠届出時に市川市役所保健センターで案内される",
    apply_url: "https://www.city.ichikawa.lg.jp/wel01/",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: 0,
      child_age_max_months: 6,
      birth_order_min: null,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: null,
    }],
  },
  {
    id: "seed-097",
    layer: "ward",
    prefecture: "千葉県",
    ward: "市川市",
    name: "市川市 子育て世帯転入促進 家賃補助",
    category: "物品・生活支援",
    summary: "市外から転入した子育て世帯に月額最大2万円・最長3年間の家賃補助を実施",
    description: "市川市独自の子育て世帯移住促進策。市外から転入した18歳未満の子どもがいる世帯（または妊婦がいる世帯）に、月額最大2万円（年間24万円）を最長3年間補助。夫婦合算年収960万円以下が対象。住宅ローンを組んでいる場合は対象外。",
    amount_monthly: 20000,
    amount_lump: null,
    amount_note: "月額最大2万円・最長3年間（年収960万円以下の転入世帯が対象）",
    apply_method: "転入後3ヶ月以内に市川市役所移住定住促進課へ申請",
    apply_url: "https://www.city.ichikawa.lg.jp/gen01/iju/",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: 0,
      child_age_max_months: 215,
      birth_order_min: null,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: 960,
    }],
  },
  // ============================================================
  // 松戸市 (千葉県)
  // ============================================================
  {
    id: "seed-098",
    layer: "ward",
    prefecture: "千葉県",
    ward: "松戸市",
    name: "松戸市 子ども医療費助成",
    category: "医療費助成",
    summary: "18歳まで医療費が無料（所得制限なし）",
    description: "松戸市では千葉県の助成に独自の上乗せをして、0歳から高校卒業（18歳年度末）まで保険診療の医療費（入院・通院）が実質無料。所得制限なし。",
    amount_monthly: null,
    amount_lump: null,
    amount_note: "高校生まで保険診療内の医療費が0円",
    apply_method: "転入時または出生届提出後、松戸市役所または各窓口で申請",
    apply_url: "https://www.city.matsudo.chiba.jp/kosodate/iryohi.html",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: 0,
      child_age_max_months: 215,
      birth_order_min: null,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: null,
    }],
  },
  {
    id: "seed-099",
    layer: "ward",
    prefecture: "千葉県",
    ward: "松戸市",
    name: "松戸市 出産・子育て応援給付金",
    category: "一時金",
    summary: "妊娠届・出生届時に計10万円相当のギフトを支給",
    description: "国の「出産・子育て応援交付金」を松戸市が実施。妊娠届出時に5万円相当、出生後に5万円相当のギフトカタログ・クーポンを支給。松戸市独自の子育て相談窓口との連携支援も受けられる。",
    amount_monthly: null,
    amount_lump: 100000,
    amount_note: "妊娠届時5万円 + 出生時5万円（合計10万円）",
    apply_method: "妊娠届出時に松戸市役所保健センターで案内される",
    apply_url: "https://www.city.matsudo.chiba.jp/kosodate/",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: 0,
      child_age_max_months: 6,
      birth_order_min: null,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: null,
    }],
  },
  {
    id: "seed-100",
    layer: "ward",
    prefecture: "千葉県",
    ward: "松戸市",
    name: "松戸市 産後ケア事業",
    category: "育児サービス",
    summary: "産後4ヶ月未満の母子を対象に宿泊・通所型産後ケアを低負担で提供",
    description: "松戸市の産後ケア事業。産後4ヶ月未満の母子を対象に、宿泊型（最大5泊）・通所型（最大7回）の産後ケアを提供。市内の協力施設（助産所・病院）を利用できる。市民税非課税世帯は利用料が減額。",
    amount_monthly: null,
    amount_lump: null,
    amount_note: "宿泊型：1泊3,000〜5,000円 / 通所型：1回1,500〜2,500円（収入により異なる）",
    apply_method: "松戸市役所保健センターへ事前申請",
    apply_url: "https://www.city.matsudo.chiba.jp/kosodate/sango-care.html",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: 0,
      child_age_max_months: 4,
      birth_order_min: null,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: null,
    }],
  },
  // ============================================================
  // 流山市 (千葉県)
  // ============================================================
  {
    id: "seed-101",
    layer: "ward",
    prefecture: "千葉県",
    ward: "流山市",
    name: "流山市 子ども医療費助成",
    category: "医療費助成",
    summary: "18歳まで医療費が無料（所得制限なし）",
    description: "流山市では千葉県の助成に独自の上乗せをして、0歳から高校卒業（18歳年度末）まで保険診療の医療費（入院・通院）が実質無料。所得制限なし。子育て支援先進都市として人口増加率全国トップクラスを誇る。",
    amount_monthly: null,
    amount_lump: null,
    amount_note: "高校生まで保険診療内の医療費が0円",
    apply_method: "転入時または出生届提出後、流山市役所または各窓口で申請",
    apply_url: "https://www.city.nagareyama.chiba.jp/section/1003/",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: 0,
      child_age_max_months: 215,
      birth_order_min: null,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: null,
    }],
  },
  {
    id: "seed-102",
    layer: "ward",
    prefecture: "千葉県",
    ward: "流山市",
    name: "流山市 保育所駅前送迎・子育てコンシェルジュ",
    category: "育児サービス",
    summary: "TX駅前に保育施設とコンシェルジュ常駐。送迎バス・一時保育・病後児保育など充実した保育サービス",
    description: "流山市が推進する「子育て支援のまちづくり」の一環。流山おおたかの森駅・南流山駅近くに子育て総合センターを設置し、コンシェルジュが保育所探しから各種支援制度の申請まで一元サポート。市内幼稚園バスの運行・病後児保育室なども完備。",
    amount_monthly: null,
    amount_lump: null,
    amount_note: "コンシェルジュ無料相談・送迎サービス（利用料別途）",
    apply_method: "流山市子育て支援センターへ直接来訪または電話予約",
    apply_url: "https://www.city.nagareyama.chiba.jp/section/1003/",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: 0,
      child_age_max_months: 71,
      birth_order_min: null,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: null,
    }],
  },
  {
    id: "seed-103",
    layer: "ward",
    prefecture: "千葉県",
    ward: "流山市",
    name: "流山市 出産・子育て応援給付金",
    category: "一時金",
    summary: "妊娠届・出生届時に計10万円相当のギフトを支給",
    description: "国の「出産・子育て応援交付金」を流山市が実施。妊娠届出時に5万円相当、出生後に5万円相当のギフトカタログ・クーポンを支給。流山市独自の子育て支援情報とあわせて提供される。",
    amount_monthly: null,
    amount_lump: 100000,
    amount_note: "妊娠届時5万円 + 出生時5万円（合計10万円）",
    apply_method: "妊娠届出時に流山市役所健康増進課で案内される",
    apply_url: "https://www.city.nagareyama.chiba.jp/section/1003/",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: 0,
      child_age_max_months: 6,
      birth_order_min: null,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: null,
    }],
  },
  // ============================================================
  // つくば市 (茨城県)
  // ============================================================
  {
    id: "seed-104",
    layer: "ward",
    prefecture: "茨城県",
    ward: "つくば市",
    name: "つくば市 子ども医療費助成",
    category: "医療費助成",
    summary: "18歳まで医療費が無料（所得制限なし）",
    description: "つくば市では茨城県の助成に独自の上乗せをして、0歳から高校卒業（18歳年度末）まで保険診療の医療費（入院・通院）が実質無料。所得制限なし。研究学園都市として子育て環境整備にも積極的。",
    amount_monthly: null,
    amount_lump: null,
    amount_note: "高校生まで保険診療内の医療費が0円",
    apply_method: "転入時または出生届提出後、つくば市役所または各窓口で申請",
    apply_url: "https://www.city.tsukuba.lg.jp/kosodate/iryohi.html",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: 0,
      child_age_max_months: 215,
      birth_order_min: null,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: null,
    }],
  },
  {
    id: "seed-105",
    layer: "ward",
    prefecture: "茨城県",
    ward: "つくば市",
    name: "つくば市 出産・子育て応援給付金",
    category: "一時金",
    summary: "妊娠届・出生届時に計10万円相当のギフトを支給",
    description: "国の「出産・子育て応援交付金」をつくば市が実施。妊娠届出時に5万円相当、出生後に5万円相当のギフトカタログ・クーポンを支給。伴走型相談支援もセット。つくば市独自のオンライン申請にも対応。",
    amount_monthly: null,
    amount_lump: 100000,
    amount_note: "妊娠届時5万円 + 出生時5万円（合計10万円）",
    apply_method: "妊娠届出時につくば市役所保健センターで案内される。オンライン申請も可",
    apply_url: "https://www.city.tsukuba.lg.jp/kosodate/",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: 0,
      child_age_max_months: 6,
      birth_order_min: null,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: null,
    }],
  },
  {
    id: "seed-106",
    layer: "ward",
    prefecture: "茨城県",
    ward: "つくば市",
    name: "つくば市 産後ケア事業",
    category: "育児サービス",
    summary: "産後4ヶ月未満の母子を対象に宿泊・通所型産後ケアを低負担で提供",
    description: "つくば市の産後ケア事業。産後4ヶ月未満の母子を対象に、宿泊型・通所型・訪問型の産後ケアを提供。市内の協力医療機関・助産所で授乳支援・育児相談・産後回復支援を受けられる。市民税非課税世帯は減額。",
    amount_monthly: null,
    amount_lump: null,
    amount_note: "宿泊型：1泊2,000〜4,000円 / 通所型：1回1,000〜2,000円（収入により異なる）",
    apply_method: "つくば市役所母子保健課へ事前申請",
    apply_url: "https://www.city.tsukuba.lg.jp/kosodate/sango.html",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: 0,
      child_age_max_months: 4,
      birth_order_min: null,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: null,
    }],
  },
  {
    id: "seed-107",
    layer: "ward",
    prefecture: "茨城県",
    ward: "つくば市",
    name: "つくば市 子育て支援センター（つどいの広場）",
    category: "育児サービス",
    summary: "市内各所に子育て支援センターを設置。未就園児と保護者が無料で遊べる場を提供",
    description: "つくば市内に複数の子育て支援センター（つどいの広場）を設置。未就園の子どもと保護者が無料で遊べる場を提供し、育児相談・親子交流・情報交換ができる。研究学園都市の特性を活かしたSTEM系ワークショップも開催。",
    amount_monthly: null,
    amount_lump: null,
    amount_note: "無料（一部プログラムは実費）",
    apply_method: "申請不要（つくば市子育て支援センターへ直接来訪）",
    apply_url: "https://www.city.tsukuba.lg.jp/kosodate/center.html",
    status: 'approved',
    policy_conditions: [{
      child_age_min_months: 0,
      child_age_max_months: 71,
      birth_order_min: null,
      birth_order_max: null,
      income_min_man_yen: null,
      income_max_man_yen: null,
    }],
  },
]
